### ISSUE TITLE
ocsp.apple.com

### ISSUE THREAD

**Issue by spacexnasa** [Loyalsoldier/clash-rules#10]
可以给这个ocsp.apple.com  加入到代理里面去不？

**Comment by Loyalsoldier** [comment]
只要把 proxy 列表放置在 direct 列表的上面（前面），即可对 `ocsp.apple.com` 进行代理。或者在 direct 列表的上面（前面）加入以下规则：

```
DOMAIN,ocsp.apple.com,PROXY
```
