### ISSUE TITLE
修改配置文件重启后出错

### ISSUE THREAD

**Issue by taoluojing30** [Loyalsoldier/clash-rules#100]
time="2022-06-24T20:09:55+08:00" level=info msg="Start initial rule provider greatfire"
time="2022-06-24T20:09:56+08:00" level=fatal msg="Parse config error: initial rule provider greatfire error: 
Get \"https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/greatfire.txt\": 
lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
请问这是什么问题。

**Comment by Loyalsoldier** [comment]
DNS 污染或网络问题。
