### ISSUE TITLE
can not acess zhihu

### ISSUE THREAD

**Issue by alexlavigne** [Loyalsoldier/clash-rules#102]
使用了最新的黑名单模式，无法访问知乎。

同一个规则、机器、浏览器下，可正常访问 cn.bing.com, bilibili.com, music.163.com 和
google.com, youtube.com 并正常切换内外网。

但是访问知乎时显示无法上网:

![Screenshot_20220710-001449_Chrome.jpg](https://user-images.githubusercontent.com/35389180/178116434-e374195d-3565-49c5-9884-a3d96f9ab582.jpg)

而且日志中没看到知乎相关请求

![Screenshot_20220710-002249_Clash for Android.jpg](https://user-images.githubusercontent.com/35389180/178116473-ba1f79c0-e50b-477e-b495-9e89a483cf4f.jpg)

尝试将

  - DOMAIN,zhihu.com,DIRECT
加入rules节点，无效

尝试去掉   
- RULE-SET,reject,REJECT

无效

尝试过chrome,edge,firefox都是同样结果，另外不走proxy的应用via浏览器访问知乎正常

手机是三星，安卓版本12

**Comment by Loyalsoldier** [comment]
看你的问题描述，不是规则问题
