### ISSUE TITLE
proxy和direct都有特斯拉的地址，会导致Tesla的app连不上车

### ISSUE THREAD

**Issue by c0ldian** [Loyalsoldier/clash-rules#103]
需要删掉proxy里tesla相关的

**Comment by Loyalsoldier** [comment]
Tesla app 在中国大陆用的是什么域名？

**Comment by c0ldian** [comment]
> Tesla app 在中国大陆用的是什么域名？

tesla.cn

**Comment by Loyalsoldier** [comment]
规则里没有 `tesla.cn` 这个域名

**Comment by c0ldian** [comment]
> 规则里没有 `tesla.cn` 这个域名

我以为你问的是中国区官网。
规则里的话，直接在proxy和direct里面搜tesla，都有个tesla-cdn.thron.com，tesla.com和teslamoters.com
个人猜测应该是tesla-cdn不能用proxy。我把它们三个全从proxy删了，因为tesla.com和teslamotors.com国内都是能直接访问的
