### ISSUE TITLE
`click.redditmail.com` 被拒绝

### ISSUE THREAD

**Issue by myuanz** [Loyalsoldier/clash-rules#104]
`click.redditmail.com` 是 reddit 的邮件订阅跳转用中间域名, 不是什么奇怪的域名. 

![image](https://user-images.githubusercontent.com/25359546/179986512-89b2f462-9c8a-401b-8405-4ca3f0ae20a6.png)

感谢这个规则集合

**Comment by Loyalsoldier** [comment]
已在上游修复：https://github.com/Loyalsoldier/v2ray-rules-dat/commit/0ea31314fba8f0961d7074cc15454e4f272b2b15
