### ISSUE TITLE
白名单模式下Proxy规则无法使用

### ISSUE THREAD

**Issue by blngxj** [Loyalsoldier/clash-rules#106]
在白名单模式下有如下三条规则
rules:
  - RULE-SET,proxy,PROXY
  - RULE-SET,telegramcidr,PROXY
  - MATCH,PROXY

在Rule Providers 中 PROXY 对应的网址为
https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
我已修改hosts，确定在未经过代理的情况下可以直接访问该网址。

从日志中摘取内容
time="2022-07-29T01:07:47+08:00" level=fatal msg="Parse config error: rules[8] [RULE-SET,proxy,PROXY] error: proxy [PROXY] not found"

其他 DIRECT 直连规则均已成功初始化，PROXY 规则却无法加载。将这三条规则删除可以正常使用CFW，否则出现错误。

可以的话，请帮忙解答，非常感谢。

**Comment by Loyalsoldier** [comment]
默认不存在 `PROXY` 这个策略，需要在 `proxies` 或 `proxy-groups` 中新增，参考：https://github.com/Loyalsoldier/clash-rules/blob/hidden/config.yaml

**Comment by blngxj** [comment]
这是来自QQ邮箱的假期自动回复邮件。

您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
