### ISSUE TITLE
需要直连的应用列表中存在的`aria2c{.exe}`可能会使Aria2无法下载外网链接

### ISSUE THREAD

**Issue by nukemiko** [Loyalsoldier/clash-rules#109]
如果在浏览器里借助类似于 [Aria2 下载器集成组件](https://addons.mozilla.org/firefox/addon/aria2-integration) 的插件，通过 Aria2 从外网下载文件时，由于 `aria2c` 和 `aria2c.exe` 存在于直连应用列表中，会导致浏览器和 Aria2 的代理状态不一致，应当被代理的流量不被代理。在从外网下载文件时，如果网络环境不好，这一规则会导致下载失败。其他下载器应用（例如 `fdm`）也存在此问题。

如果将 `aria2c` 和 `aria2c.exe` 加入直连应用列表是为了防止代理 BT 流量和无意间通过代理大流量下载，那么建议为此类下载器单独建立一个规则，方便根据需要切换。

**Comment by Loyalsoldier** [comment]
建议自行修改配置
