### ISSUE TITLE
无法切换到此配置文件

### ISSUE THREAD

**Issue by yayyayyay7** [Loyalsoldier/clash-rules#110]
![image](https://user-images.githubusercontent.com/17941036/184282826-a4d62e38-007c-439a-a543-935b9818a65e.png)
我使用的最新版clash, 规则中似乎没有rule set这个类型？是这个原因？
![image](https://user-images.githubusercontent.com/17941036/184282901-197a8375-b442-4e93-9594-07001f079092.png)

**Comment by Loyalsoldier** [comment]
需要新增一个名为 `PROXY` 的 proxy
