### ISSUE TITLE
报错，no data

### ISSUE THREAD

**Issue by yayyayyay7** [Loyalsoldier/clash-rules#112]
![image](https://user-images.githubusercontent.com/17941036/184369812-4c1b828f-337f-490e-b79d-739b55660ac1.png)
我搜索之前关闭的问题讨论no data的，说是dns或网络问题。但是我换了opendns后出现新的报错如图
![image](https://user-images.githubusercontent.com/17941036/184369641-0ba9b15c-af3a-44d0-ada6-d76d7e4cc74e.png)
![image](https://user-images.githubusercontent.com/17941036/184370303-6d731298-2b72-4b4f-a433-b3da7f35b9f1.png)

**Comment by Loyalsoldier** [comment]
网络问题
