### ISSUE TITLE
无法切换配置文件

### ISSUE THREAD

**Issue by yayyayyay7** [Loyalsoldier/clash-rules#113]
这是什么问题啊？请大佬解答
![image](https://user-images.githubusercontent.com/17941036/184472026-1997f818-bf2c-4afe-bf1e-f1da306fba95.png)
因为在线更新报错，换dns无法解决，我将本站.txt规则文件下载本地改成yaml放入ruleset
![image](https://user-images.githubusercontent.com/17941036/184472068-82753958-8c5d-4809-acdc-04dba50d56a8.png)

**Comment by Loyalsoldier** [comment]
`type` 改成 `file`；去掉 `url` 那一行
