### ISSUE TITLE
在线无法更新，下载规则安装后，新的报错

### ISSUE THREAD

**Issue by yayyayyay7** [Loyalsoldier/clash-rules#114]
下面贴了我的配置文件代码，规则下载到ruleset文件夹放在这里对吧 ？C:\Users\one\.config\clash\ruleset，还是说放在这里？ C:\Program Files\Clash for Windows 

![image](https://user-images.githubusercontent.com/17941036/184519291-eabf31f3-31d3-4aed-a772-b27965421434.png)

proxies:
  - name: "PROXY"
    type: ss
    server: 保密
    port: 10001
    cipher: chacha20-ietf-poly1305
    password: ""
    udp: true

proxy-groups:
  - name: "relay"
    type: relay
    proxies:
      - PROXY

  - name: "auto"
    type: url-test
    proxies:
      - PROXY
    # tolerance: 150
    # lazy: true
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

 
  - name: "fallback-auto"
    type: fallback
    proxies:
      - PROXY
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  - name: "load-balance"
    type: load-balance
    proxies:
      - PROXY
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # strategy: consistent-hashing # or round-robin

  - name: Proxy
    type: select
    # disable-udp: true
    proxies:
      - PROXY
 
 
  - name: en1
    type: select
    interface-name: en1
    routing-mark: 6667
    proxies:
      - DIRECT 

rule-providers:
  reject:
    type: file
    behavior: domain
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: file
    behavior: domain
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: file
    behavior: domain
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: file
    behavior: domain
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: file
    behavior: domain
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: file
    behavior: domain
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: file
    behavior: domain
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: file
    behavior: domain
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: file
    behavior: domain
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: file
    behavior: domain
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: file
    behavior: ipcidr
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: file
    behavior: ipcidr
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: file
    behavior: ipcidr
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: file
    behavior: classical
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY

**Comment by Loyalsoldier** [comment]
到 Clash for Windows 客户端的仓库去提问

**Comment by yayyayyay7** [comment]
我把telegramcidr相关字段删了就能用了，这是客户端的事吗

**Comment by yayyayyay7** [comment]
> 到 Clash for Windows 客户端的仓库去提问

我把telegramcidr相关字段删了就能用了，这是客户端的事吗？
