### ISSUE TITLE
订阅更新问题

### ISSUE THREAD

**Issue by Qvisl9** [Loyalsoldier/clash-rules#116]
除了github可以订阅外，还有别的订阅地址吗，国内dns污染严重，无法更新。

**Comment by Loyalsoldier** [comment]
https://github.com/Loyalsoldier/clash-rules/commit/fa12eabc89ae3f373d556f0d0846909a691d19aa

**Comment by Qvisl9** [comment]
我是不是只要复制rule-providers:里的内容到配置文件里，这样如果github无法更新，会自动用jsdelivr更新。

Loyalsoldier ***@***.***> 于2022年8月19日周五 00:50写道：
