### ISSUE TITLE
tunein app

### ISSUE THREAD

**Issue by sanziliu** [Loyalsoldier/clash-rules#117]
你好，

使用tunein app（iOS，macOS），很多频道检测不在美国服务区域不能播放，于是使用surge抓包，很容易就设定好了ruleset分流（见末尾），解决了这个问题。

但是家里软路由使用openclash，我尝试了很多次都无法正确设置成功相应ruleset（PROCESS-NAME/DOMAIN-SUFFIX等设置），也就是无法实现自动分流。反复看logfile，感觉PROCESS-NAME都抓不到，不知道这里的规则有没有这个。

打扰了

++++++++

Surge ruleset
# > Tunein
USER-AGENT,Tunein
DOMAIN-SUFFIX,tunein.com
DOMAIN-SUFFIX,radiotime.com

**Comment by Loyalsoldier** [comment]
Clash 里没有 User Agent 的规则。既然已经抓包了，把抓包的域名全走代理应该就可以啊。
