### ISSUE TITLE
关于规则内写法疑问

### ISSUE THREAD

**Issue by koonuz** [Loyalsoldier/clash-rules#118]
举例：  规则 - '+.google' 的写法

请问 - '+.google' 的写法是否默认仅识别以 .google 为后缀的域名格式，即类似.com、.net、.org这样的存在。
 - '+.google' 的写法无法识别当域名为 xxx.google.cc 的分流，即 - '+.google' 不等于DOMAIN-KEYWORD的用法？

**Comment by Loyalsoldier** [comment]
不等于
