### ISSUE TITLE
在applications.txt中增加sslocal(.exe)？

### ISSUE THREAD

**Issue by Dr-Bluemond** [Loyalsoldier/clash-rules#119]
最新版本的shadowsocks-rust的Release中，客户端二进制文件的名字是sslocal，不过目前规则只有ss-local，没能直接匹配成功，希望可以加上sslocal。

**Comment by Loyalsoldier** [comment]
已添加 https://github.com/Loyalsoldier/clash-rules/commit/895cc057a670316fb0ca13414407bbb063997757
