### ISSUE TITLE
telegram的IP

### ISSUE THREAD

**Issue by forgmissyou** [Loyalsoldier/clash-rules#12]
建议从 http://bgp.he.net 抓取IP，我自己整理的
payload:
  - '67.198.55.0/24'
  - '91.108.4.0/22'
  - '91.108.8.0/22'
  - '91.108.12.0/22'
  - '91.108.16.0/22'
  - '91.108.20.0/22'
  - '91.108.20.0/23'
  - '91.108.56.0/22'
  - '91.108.56.0/23'
  - '95.161.64.0/20'
  - '95.161.84.0/23'
  - '109.239.140.0/24'
  - '149.154.160.0/22'
  - '149.154.164.0/22'
  - '149.154.168.0/22'
  - '149.154.172.0/22'
  - '2001:67c:4e8::/48'
  - '2001:b28:f23c::/48'
  - '2001:b28:f23d::/48'
  - '2001:b28:f23f::/48'
  - '2001:b28:f242::/48'

**Comment by Loyalsoldier** [comment]
Telegram 自己出示的 IP 列表岂不是更准吗？https://core.telegram.org/resources/cidr.txt

**Comment by Remonli** [comment]
@Loyalsoldier  他们自己公布的并不更准哇  91.108.23.100 这个地址就没公布，应该属于91.108.20.0/22

**Comment by Loyalsoldier** [comment]
@Remonli  Thanks for notice.

I have refined Telegram CIDR in https://github.com/Loyalsoldier/clash-rules/commit/5ab8e297508f71a855c2f85b93b3c7e093d15d3b and https://github.com/Loyalsoldier/clash-rules/commit/7f13203f068331fab3a0e0de6e7622bcc27dea6e
