### ISSUE TITLE
谷歌翻译的api被墙

### ISSUE THREAD

**Issue by duan-dky** [Loyalsoldier/clash-rules#123]
![image](https://user-images.githubusercontent.com/74866582/192740955-e7775c9e-efc2-4ced-818f-02fcf6ec7dfc.png)
*如图，今天早上发现chrome自带翻译不能用，tcpping发现translate.googleapis.com的443端口全部不通，今天才有的现象，建议添加translate.googleapis.com这个域名到代理，原规则是直连域名*

**Comment by ra1nbow2000** [comment]
![image](https://user-images.githubusercontent.com/32125748/192919722-c30b9c3b-56f7-4b47-9d20-4c3d66aac8a4.png)
武汉电信已经不能直连谷歌翻译api了

**Comment by Loyalsoldier** [comment]
请到上游 https://github.com/felixonmars/dnsmasq-china-list 反馈

**Comment by duan-dky** [comment]
好
