### ISSUE TITLE
是否可以收集一个appapi集合

### ISSUE THREAD

**Issue by XhL6996** [Loyalsoldier/clash-rules#125]
当前大多数国内软件都响应要求显示IP属地，是否可以收集一下这些公司获取IP的api的域名或者IP，从而只代理这部分流量，来更改IP属地。
如B站，其流量大头是视频CDN，但访问视频CDN的IP并不影响IP属地的显示。根据个人实践，只代理app.bilibili.com、api.bilibili.com等少数几个域名即可改变发表评论时属地的显示。所以就没必要代理整个B站的流量。而且国内机器带宽普遍很小，比如1Mbps，只代理这些获取IP的api是比较合理的选择。

**Comment by Loyalsoldier** [comment]
使用场景太窄

**Comment by XhL6996** [comment]
好吧，只能说不是刚需吧，毕竟这些域名/IP其实是可以直连的。但是如果有这么一个规则的话，感觉很多人还是愿意使用的。

**Comment by iKira** [comment]
你为什么不自己在配置文件里增加一个rule-providers？以后缺什么api域名，自己往txt里填然后在线更新下配置就行了。

**Comment by XhL6996** [comment]
> 你为什么不自己在配置文件里增加一个rule-providers？以后缺什么api域名，自己往txt里填然后在线更新下配置就行了。

我当然自己怎么玩都可以了，但是众人拾柴火焰高嘛。
