### ISSUE TITLE
建议 reject.txt 删除 mx.technolutions.net

### ISSUE THREAD

**Issue by edgexyz** [Loyalsoldier/clash-rules#13]
域名下不仅包含广告还有一些大学账号申请/夏校申请使用的跳转链接，屏蔽此域名可能会导致大量误伤
<img width="1440" alt="Screen Shot 2020-12-13 at 23 52 21" src="https://user-images.githubusercontent.com/32131214/102016939-904ca000-3d9e-11eb-9af5-4cd709eeb35f.png">

**Comment by Loyalsoldier** [comment]
`mx.technolutions.net` 跟截图有啥关系？

**Comment by edgexyz** [comment]
看左下.... UChicago 对邮件内的跳转链接使用的是 mx.technolutions.net

**Comment by edgexyz** [comment]
https://forums.malwarebytes.com/topic/239104-technolutionsnet/

好像是使用 technolutions.com 家产品 Slate 的学校发邮件都会把 url rewrite 成 https://mx.technolutions.net/...

**Comment by Loyalsoldier** [comment]
Fixed in https://github.com/Loyalsoldier/v2ray-rules-dat/commit/e4b643244b3ffeec02dddbf4b040c19fd220605b
