### ISSUE TITLE
为啥services.googleapis.cn匹配direct

### ISSUE THREAD

**Issue by iislong** [Loyalsoldier/clash-rules#131]
我在direct中没有找services.googleapis.cn，这是怎么匹配的？

Play store应用更新已通过PROCESS-NAME解决

**Comment by iislong** [comment]
找到原因了，匹配了- '+.cn'

**Comment by iislong** [comment]
找到原因了，匹配了- '+.cn'

**Comment by InsulateJustf** [comment]
> 找到原因了，匹配了- '+.cn'

感谢提醒，刚从别的规则集切换过来就遇到了这种问题😂

**Comment by listenerri** [comment]
@Loyalsoldier 我翻了下 issues 发现 2021 年就有人提出这个问题了，请问为什么没有修复呢？涉及的域名好像有两个：

- services.googleapis.cn
- googleapis.cn

**Comment by listenerri** [comment]
> @Loyalsoldier 我翻了下 issues 发现 2021 年就有人提出这个问题了，请问为什么没有修复呢？涉及的域名好像有两个：
> 
>     * services.googleapis.cn
> 
>     * googleapis.cn

搜了下 ruleset 其中 gfw 里有 '+.googleapis.cn'，不过 README 中推荐的 白名单模式 rules 里没有加 gfw
