### ISSUE TITLE
proxy.txt在Android的Clash应用上无法正常解析、启用，报错unsupported protocol

### ISSUE THREAD

**Issue by mo-han** [Loyalsoldier/clash-rules#134]
- 仅此一个遇到该问题，其他的rule都OK
- 详情已写在相关app的项目issue板块，此处不再复述，点击查看https://github.com/MetaCubeX/ClashMetaForAndroid/issues/20

**Comment by Loyalsoldier** [comment]
应该是上游 app 的问题
