### ISSUE TITLE
RULE-SET applications after everything else (for torrents)

### ISSUE THREAD

**Issue by imr0** [Loyalsoldier/clash-rules#142]
Hi,

I think it is better to have `RULE-SET,applications,DIRECT` after everything else and just before `MATCH`, at least as long as torrent UDP connections are concerned. Often direct connections to certain trackers are blocked, so it is better to first resolve these via a proxy. With the original ordering, I had difficulties connecting to various trackers.

**Comment by Loyalsoldier** [comment]
Will not change. You can change your own configuration file.
