### ISSUE TITLE
google play 只能查看不能下载的问题

### ISSUE THREAD

**Issue by derry96** [Loyalsoldier/clash-rules#147]
使用的是白名单模式, play商店只能查看不能下载, 通过添加下面两条规则后解决:

- DOMAIN-SUFFIX,services.googleapis.cn,DIRECT
- DOMAIN-SUFFIX,xn--ngstr-lra8j.com,DIRECT

所以建议一下, 能否将这两条规则加入订阅

**Comment by kelefy** [comment]
加了这两条规则，，好像也不行

**Comment by kelefy** [comment]
hi , @derry96 

我加入了这两条规则也不行，，，请问有什么新规则吗？

**Comment by derry96** [comment]
> hi , @derry96
> 
> 我加入了这两条规则也不行，，，请问有什么新规则吗？

尝试清空dns缓存, 如果仍然失败可以参考这个帖子: https://www.v2ex.com/t/696735

**Comment by kelefy** [comment]
> 使用的是白名单模式, play商店只能查看不能下载, 通过添加下面两条规则后解决:
> 
> * DOMAIN-SUFFIX,services.googleapis.cn,DIRECT
> * DOMAIN-SUFFIX,xn--ngstr-lra8j.com,DIRECT
> 
> 所以建议一下, 能否将这两条规则加入订阅

我看帖子：https://www.v2ex.com/t/696735
写的是r16---sn-ni57rn7e.xn--ngstr-lra8j.com

**Comment by derry96** [comment]
> > 使用的是白名单模式, play商店只能查看不能下载, 通过添加下面两条规则后解决:
> > 
> > * DOMAIN-SUFFIX,services.googleapis.cn,DIRECT
> > * DOMAIN-SUFFIX,xn--ngstr-lra8j.com,DIRECT
> > 
> > 所以建议一下, 能否将这两条规则加入订阅
> 
> 我看帖子：https://www.v2ex.com/t/696735 写的是 r16---sn-ni57rn7e.xn--ngstr-lra8j.com 而上面贴的是 xn--ngstr-lra8j.com

https://github.com/Dreamacro/clash/wiki/Configuration%3A-Introduction#rules

**Comment by kelefy** [comment]
噢，小白了。。谢谢
