### ISSUE TITLE
clash for windows更新0.20.14之后出错

### ISSUE THREAD

**Issue by ShadowEmbrace** [Loyalsoldier/clash-rules#149]
initial rule provider proxy error: get "..." EOF
那边好像是调整了策略，这边的使用方式是不是要改变？

**Comment by Loyalsoldier** [comment]
网络问题，多尝试几次

**Comment by Gui-Gu** [comment]
> 网络问题，多尝试几次
![image](https://user-images.githubusercontent.com/95043489/215677797-457f5cb6-36e1-46ea-b712-8c827b11d64b.png)

win v 0.20.15 一直报错，但同样的配置Ubuntu正常运行

**Comment by Gui-Gu** [comment]
> > 网络问题，多尝试几次
> > ![image](https://user-images.githubusercontent.com/95043489/215677797-457f5cb6-36e1-46ea-b712-8c827b11d64b.png)
> 
> win v 0.20.15 一直报错，但同样的配置Ubuntu正常运行

https://github.com/Loyalsoldier/clash-rules/issues/92#issuecomment-1150537430
