### ISSUE TITLE
direct.txt cn 问题

### ISSUE THREAD

**Issue by spacexnasa** [Loyalsoldier/clash-rules#15]
你好，如果我不使用国内的 dns 解析，域名里面有 cn 结尾的话，会有问题，可以去掉么？

- '+.cn'
这个

作者可以试试下   juejin.cn 用 1.1.1.1  8.8.8.8 解析，出现的解析 ip 非国内，这样，clashx 还是会直接连接解析出来的美国 ip，这样，juejin.cn 就不能访问了，还有 www.sian.com.cn 的，也是一样的

**Comment by Loyalsoldier** [comment]
想要 .cn 域名直连，就加一条 `DOMAIN-SUFFIX,cn,DIRECT` 在 reject 规则下面。使用国外 DNS 当然会解析出国外的 IP 地址
