### ISSUE TITLE
谷歌商店下载不了APP

### ISSUE THREAD

**Issue by lonelydespair** [Loyalsoldier/clash-rules#152]
作者大佬，您好！
一直用的这个规则，非常好用，最近发现一个问题，在谷歌商店下载不了APP，一直等待中，切换google.txt为代理也不行，后面换成ACL4SSR规则后，可以下载了，麻烦有空的时候修复下，很想继续用这个规则。

**Comment by Loyalsoldier** [comment]
建议自行处理。参考 https://github.com/Loyalsoldier/clash-rules/issues/147
