### ISSUE TITLE
白名单模式,IOS设备收不到推送通知

### ISSUE THREAD

**Issue by Ch1cC** [Loyalsoldier/clash-rules#153]
- vmess grpc 协议
- rules:
  - RULE-SET,applications,🌐 全球直连
  - DOMAIN,clash.razord.top,🌐 全球直连
  - DOMAIN,yacd.haishan.me,🌐 全球直连
  - RULE-SET,private,🌐 全球直连
  - RULE-SET,reject,⛔️ 全球拦截
  - RULE-SET,icloud,🌐 全球直连
  - RULE-SET,apple,🌐 全球直连
  - RULE-SET,google,🌐 全球直连
  - RULE-SET,direct,🌐 全球直连
  - RULE-SET,lancidr,🌐 全球直连
  - RULE-SET,cncidr,🌐 全球直连
  - RULE-SET,telegramcidr,♻️ 自动选择
  - RULE-SET,proxy,♻️ 自动选择
  - GEOIP,LAN,🌐 全球直连,no-resolve
  - GEOIP,CN,🌐 全球直连,no-resolve
  - MATCH,♻️ 自动选择

**Comment by dichen-cd** [comment]
@Ch1cC 这个问题你解决了吗？Android同样收不到推送通知。关闭Clash或者换用其他profile之后，积压的推送通知会一口气全弹出来。
