### ISSUE TITLE
Apple 外区播客单集不可用

### ISSUE THREAD

**Issue by DEabcdp** [Loyalsoldier/clash-rules#160]
使用的是黑名单，Apple的一些外区Podcasts会出现“单集不可用”提示。

<img width="260" alt="image" src="https://user-images.githubusercontent.com/62452364/222870471-88abab14-57bd-4cb5-b6ba-058b840a0367.png">

**Comment by Loyalsoldier** [comment]
使用白名单应该可以

**Comment by DEabcdp** [comment]
白名单也不行，得全局PROXY才可以。黑名单/白名单应该将外区podcasts的域名加入代理里面。
