### ISSUE TITLE
规则导致steam下载缓慢

### ISSUE THREAD

**Issue by austiecodes** [Loyalsoldier/clash-rules#161]
看了一下就是 `*.steamcontent.com` 这个域名被加到 `proxy` 里面了，导致 steam 下载的 cdn 相关域名走代理。希望能把这个域名移动 `direct` 下面。

>   - DOMAIN-SUFFIX,steamcontent.com,DIRECT
>   - DOMAIN-SUFFIX,steamchina.com,DIRECT
>   - DOMAIN,csgo.wmsj.cn,DIRECT
>   - DOMAIN,dota2.wmsj.cn,DIRECT
>   - DOMAIN,wmsjsteam.com,DIRECT
>   - DOMAIN,dl.steam.clngaa.com,DIRECT
>   - DOMAIN,dl.steam.ksyna.com,DIRECT
>   - DOMAIN,st.dl.bscstorage.net,DIRECT
>   - DOMAIN,st.dl.eccdnx.com,DIRECT
>   - DOMAIN,st.dl.pinyuncloud.com,DIRECT
>   - DOMAIN,steampipe.steamcontent.tnkjmec.com,DIRECT
>   - DOMAIN,steampowered.com.8686c.com,DIRECT
>   - DOMAIN,steamstatic.com.8686c.com,DIRECT
>   - DOMAIN,steambroadcast.akamaized.net,DIRECT
>   - DOMAIN,steamcdn-a.akamaihd.net,DIRECT
>   - DOMAIN,steamcommunity-a.akamaihd.net,DIRECT
>   - DOMAIN,steamstore-a.akamaihd.net,DIRECT
>   - DOMAIN,steamusercontent-a.akamaihd.net,DIRECT
>   - DOMAIN,steamuserimages-a.akamaihd.net,DIRECT

我目前是把这些 steam cdn相关的域名加到了 `RULE-SET,proxy,PROXY` 的前面，暂时解决问题。

**Comment by Loyalsoldier** [comment]
感谢提醒，但本项目不做特殊处理。
