### ISSUE TITLE
怎么转化成 openclash 能用的规则 ？

### ISSUE THREAD

**Issue by wzy105** [Loyalsoldier/clash-rules#169]
如题。
   谢谢各位老师傅

**Comment by Loyalsoldier** [comment]
https://github.com/vernesong/OpenClash/wiki/%E8%A7%84%E5%88%99%E8%AE%BE%E7%BD%AE%EF%BC%88%E8%AE%BF%E9%97%AE%E6%8E%A7%E5%88%B6%EF%BC%89

**Comment by wzy105** [comment]
> https://github.com/vernesong/OpenClash/wiki/%E8%A7%84%E5%88%99%E8%AE%BE%E7%BD%AE%EF%BC%88%E8%AE%BF%E9%97%AE%E6%8E%A7%E5%88%B6%EF%BC%89

![1679876884587_edit_12131685504918](https://user-images.githubusercontent.com/117211092/227814879-56fb2a90-7361-46bf-8d57-f5159fcedb4f.jpg)
不知道为什么配置好了 启动 会错误
