### ISSUE TITLE
battle.net域名在proxy规则里

### ISSUE THREAD

**Issue by cjwddtc** [Loyalsoldier/clash-rules#17]
battle.net是暴雪战网的域名，似乎至少不应该默认就是用代理？这样干国服就没办法正常登录了。

**Comment by Loyalsoldier** [comment]
暴雪相关的域名来自 https://github.com/v2fly/domain-list-community/blob/master/data/blizzard

可以具体列出 `battle.net` 哪些子域名在暴雪国服中被使用吗？

**Comment by cjwddtc** [comment]
我们通过clash的连接跟踪（没有完整的抓包，太麻烦了），目前国服战网登录状态下，有telemetry-in.battle.net和cn.actual.battle.net，登录我玩的星际二的话还有cn-s2.logon.battlenet.com.cn和client02.pdl.wow.battlenet.com.cn
其他游戏我甚至都没有下载所以没办法测试。

**Comment by Loyalsoldier** [comment]
试试把 `cn.actual.battle.net` 设置为直连。

**Comment by cjwddtc** [comment]
我知道如何设置规则，我只是觉得暴雪系列的游戏至少默认都应该走的是直连，而不是代理，即使要支持代理也应该是额外的添加一个可以手动控制的group。

**Comment by Loyalsoldier** [comment]
添加上面规则之后，国服就可以登录了，是吗？可以的话，我就把域名 `cn.actual.battle.net` 添加到直连列表里。

**Comment by cjwddtc** [comment]
我其实直接把battle.net整个都直连了，并没有具体的测试。
但我个人认为，battle.net整个默认是不应该走代理的，或者说暴雪系列的游戏在国内（玩外服另外算）访问本来就有着足够良好的体验，因此我不认为对于正常使用国服的玩家需要默认对整个暴雪系列的域名进行代理。而理论上大多数人玩的应该都是国服，即使玩外服，通常也有游戏加速器而不是使用clash进行游戏加速。

**Comment by Loyalsoldier** [comment]
https://github.com/v2fly/domain-list-community/pull/361
