### ISSUE TITLE
www.beian.gov.cn 分流进代理了

### ISSUE THREAD

**Issue by komori-flag** [Loyalsoldier/clash-rules#176]
![QQ截图20230421151412](https://user-images.githubusercontent.com/105255344/233568067-2560c7a3-41b9-4067-856c-e904c23fca39.png)
![QQ截图20230421151451](https://user-images.githubusercontent.com/105255344/233568081-bb276243-8708-4cfc-9cf8-4dff15e9c78d.png)

不知为何这个网站（www.beian.gov.cn）被分流进了[GreatFire 域名列表 greatfire.txt](https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt)列表里，麻烦大佬来看看。

**Comment by Loyalsoldier** [comment]
由于上游项目 [@Loyalsoldier/cn-blocked-domain](https://github.com/Loyalsoldier/cn-blocked-domain) 已归档（archived），其被封域名数据已过期，故已把本项目的 greatfire 域名列表中的所有后添加的自定义域名移除，与上上游项目（[@v2fly/domain-list-community](https://github.com/v2fly/domain-list-community)）的 [greatfire 列表](https://github.com/v2fly/domain-list-community/blob/master/data/greatfire)保持一致。请知悉。

也就是说：域名 www.beian.gov.cn 已不存在于本项目 greatfire 列表，且本项目 greatfire 列表已不被推荐使用。
