### ISSUE TITLE
希望在“需要直连的常见软件列表”内添加“Motrix”进程

### ISSUE THREAD

**Issue by DustinWin** [Loyalsoldier/clash-rules#179]
[Motrix](https://github.com/agalwood/Motrix) 也是一个比较热门的 bt 下载软件，近期已经开始更新客户端
<img src="https://user-images.githubusercontent.com/45238096/235239872-476c422e-9aad-4d4c-8fbc-fd6f3b6a51b3.png" width=60%>  

希望能在“需要直连的常见软件列表 applications.txt”内添加如下进程：
```
- PROCESS-NAME,Motrix
- PROCESS-NAME,Motrix.exe
```

**Comment by Loyalsoldier** [comment]
真正执行下载任务的是 aria2c.exe，已存在列表中。

**Comment by DustinWin** [comment]
> 真正执行下载任务的是 aria2c.exe，已存在列表中。

好的，谢谢！

**Comment by DustinWin** [comment]
> > 真正执行下载任务的是 aria2c.exe，已存在列表中。
> 
> [@Loyalsoldier](https://github.com/Loyalsoldier) 你好，那微信不是更常见，为什么也不在列表呢？

这些收录在 direct.txt 里面
