### ISSUE TITLE
applications 里面规则重复

### ISSUE THREAD

**Issue by Hades-001** [Loyalsoldier/clash-rules#187]
https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt  里面第10行和第11行的内容完全一样，猜测是不是第11行少了.exe

![捕获1](https://github.com/Loyalsoldier/clash-rules/assets/30254702/ca3fbb79-4dd7-4c2f-8c61-ea42f13bcb08)

**Comment by Hades-001** [comment]
匹配的进程名应该是 Proxifier.exe

![捕获2](https://github.com/Loyalsoldier/clash-rules/assets/30254702/4fe1d123-b5c2-4a19-a391-4d647ed9881b)

**Comment by Loyalsoldier** [comment]
感谢提醒，已修复
