### ISSUE TITLE
希望增加Windows隐私跟踪拦截规则

### ISSUE THREAD

**Issue by TPCTPCTPC** [Loyalsoldier/clash-rules#19]
如题，Clash用户中有相当大一部分是Windows用户，目前的Clash规则更偏向于Mac。希望能增加[WindowsSpyBlocker](https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt)和NextDNS的[Windows native blocker](https://raw.githubusercontent.com/nextdns/metadata/master/privacy/native/windows)作为独立的规则列表来加强win的隐私保护。

**Comment by Loyalsoldier** [comment]
项目 https://github.com/Loyalsoldier/v2ray-rules-dat 正在测试 WindowsSpyBlocker 的效果，目前有些小 bug：https://github.com/Loyalsoldier/v2ray-rules-dat/issues/71

观望中……
