### ISSUE TITLE
关于配置文件的no-resolve

### ISSUE THREAD

**Issue by toyo2333** [Loyalsoldier/clash-rules#193]
这个局域网ip，是不是加上 no-resolve才对？

payload:
  - '0.0.0.0/8'
  - '10.0.0.0/8'
  - '100.64.0.0/10'
  - '127.0.0.0/8'
  - '169.254.0.0/16'
  - '172.16.0.0/12'
  - '192.0.0.0/24'
  - '192.0.2.0/24'
  - '192.88.99.0/24'
  - '192.168.0.0/16'
  - '198.18.0.0/15'
  - '198.51.100.0/24'
  - '203.0.113.0/24'
  - '224.0.0.0/3'
  - '::1/128'
  - 'fc00::/7'
  - 'fe80::/10'

不然都走一遍域名解析？（假定前面的域名规则都没有命中的极端情况下）

**Comment by Loyalsoldier** [comment]
内网域名需要 DNS 解析

**Comment by toyo2333** [comment]
> 内网域名需要 DNS 解析

rules:

  **- RULE-SET,private,DIRECT**

  **- RULE-SET,lancidr,DIRECT**

规则里，内网域名规则在前面，不是已经走了Direct了么，为什么还要再进行域名解析再查一边下面的这个lancidr规则？

**Comment by Loyalsoldier** [comment]
公司会使用公司特有的内网域名啊。你可以不使用内网 IP 的 RULE-SET 规则，而使用 geoip。GEOIP 规则可以方便添加 no-resolve
