### ISSUE TITLE
为什么白名单规则里还要指定proxy

### ISSUE THREAD

**Issue by toyo2333** [Loyalsoldier/clash-rules#194]
- RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,LAN,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,Proxy
  
请教，你个白名单模板里

- RULE-SET,proxy,PROXY 这条规则存在的意义是什么？

白名单不是有
  - MATCH,Proxy兜底么？比如youtube这个肯定是走proxy的还有必要在前面加- RULE-SET,proxy,PROXY 么？

对于   - RULE-SET,telegramcidr,PROXY 也是同样的疑问，不指定这个ip规则的情况下，使用telegram是由什么负面影响么？

请指教

**Comment by Loyalsoldier** [comment]
可以去掉，不影响。
