### ISSUE TITLE
移动宽带 更新列表一直提示tls握手失败

### ISSUE THREAD

**Issue by wzy105** [Loyalsoldier/clash-rules#199]
![Screenshot_20230702_014239_com github kr328 clash](https://github.com/Loyalsoldier/clash-rules/assets/117211092/21388ca1-1aa7-4922-8729-ff4e2728637f)

最近才这样请问怎么解决 更换dns也不行

**Comment by Loyalsoldier** [comment]
可以尝试把域名 https://cdn.jsdelivr.net 换成 https://fastly.jsdelivr.net

**Comment by fatinghenji** [comment]
![Uploading Screenshot_2023-07-06-08-01-33-49_1ed813789000d97ac1c6fc69779c1198.jpg…]()
更换完问题依旧存在。
