### ISSUE TITLE
[TCP] 127.0.0.1:56230(Proxifier.exe) --> updates.discord.com:443 match RuleSet(applications) using DIRECT

### ISSUE THREAD

**Issue by RonaldinhoL** [Loyalsoldier/clash-rules#200]
感觉 Proxifier 不应该直接 direct啊，我一般不用 tun 模式，而是把想要fq的exe通过 proxifier  转发过来，但是现在直接被 direct 了，就有问题了

**Comment by CMJNB** [comment]
确实，用到proxifier的程序一般是不走系统代理无法上网的，那用proxifier的目的就是要连代理说是。
抓包什么的，可以在proxifier代理链里对接抓包软件。

**Comment by CMJNB** [comment]
应该取消对proxifier.exe的判断，由proxifier转发来的域名和ip，根据其他规则判断是否直连、代理。
