### ISSUE TITLE
applications列表增加 'BitTorrent Web' 进程

### ISSUE THREAD

**Issue by nobbbbby** [Loyalsoldier/clash-rules#201]
BitTorrent Web 是BitTorrent的一个版本。
MacOS规则如下：
- PROCESS-NAME,BitTorrent Web,DIRECT

**Comment by Rakau** [comment]
PROCESS-NAME,qBittorrent-nox,DIRECT

**Comment by Loyalsoldier** [comment]
@Rakau Done.
