### ISSUE TITLE
clash for windows 用于mac上

### ISSUE THREAD

**Issue by jaychoubaby** [Loyalsoldier/clash-rules#203]
同样的配置，用引用加载的话，windows上重试了好几次之后才能把配置加载完成，mac上无法加载配置，总是提示其中某一个引用错误，但是每一个引用单独点开是可以正常加载的，是网络问题吗还是cfw对于mac没有适配好，所以文件无法写入本地

**Comment by Loyalsoldier** [comment]
应该到 clash for windows 项目提 issue。
