### ISSUE TITLE
关于“检查站点连接是否安全”

### ISSUE THREAD

**Issue by chensimmons** [Loyalsoldier/clash-rules#206]
我平时采用的是白名单模式，然而最近打开几个不同的网站时，都出现过“检查站点连接是否安全”这个提示，
然后一直在检查，无法正常打开网页，必须切换成全局模式才能通过检查，搜了下，说是Cloudflare的防护，
所以想问问，如果真是Cloudflare的问题，那哪个规则列表有Cloudflare的域名或IP ?

另外，google列表内可能有些域名被墙了，如果google列表选择直连，可以正常打开谷歌翻译，但却无法翻译文字，必须改成代理才行，当然这问题不大，只是顺手反馈下

**Comment by Loyalsoldier** [comment]
应该是服务器 IP 被 Cloudflare 风控吧。

**Comment by chensimmons** [comment]
@Loyalsoldier 应该是，但在白名单模式下无法通过检查，切换成全局模式才能通过检查，所以想知道能不能在本地修改下某个规则列表的代理模式，让Cloudflare走代理，但我不知道是哪个规则列表。。。当然，如果是被风控，我也可以通过切换节点来解决，问题倒不大

**Comment by Loyalsoldier** [comment]
可以尝试把下面的域名设置为走代理，域名见：https://github.com/v2fly/domain-list-community/blob/master/data/cloudflare-cn

**Comment by chensimmons** [comment]
@Loyalsoldier 谢谢解答，我试试
