### ISSUE TITLE
为什么不能用 GEOIP,CN,DIRECT + MATCH,PROXY 两行配完？

### ISSUE THREAD

**Issue by chunyu-li** [Loyalsoldier/clash-rules#208]
纯小白，有个奇怪的问题哈：

- GEOIP,CN,DIRECT
- MATCH,PROXY

这两行不就能保证国内ip直连，国外ip代理吗？为啥还要配那么多规则？

**Comment by Loyalsoldier** [comment]
这样配置的话，所有域名都需要在本地进行 DNS 解析，会导致 DNS 泄漏（你使用的 DNS 服务提供商知道你访问了什么敏感域名）。不在乎 DNS 泄漏的话，可以这么配置。

**Comment by chunyu-li** [comment]
谢谢您的解答，但我还是有一个问题，为什么要在规则集里设置直连的规则？
那些域名既然可以直连，那就说明不包含敏感内容，那就不怕DNS泄漏，直接用 GEOIP,CN,DIRECT 概括了不就好了？

**Comment by Loyalsoldier** [comment]
代理域名列表里有可能有直连域名，反之亦然。谁放在上方，谁优先级更高。

**Comment by lightionight** [comment]
> 这样配置的话，所有域名都需要在本地进行 DNS 解析，会导致 DNS 泄漏（你使用的 DNS 服务提供商知道你访问了什么敏感域名）。不在乎 DNS 泄漏的话，可以这么配置。

这样说来, 自建一个本地无污染的dns解析,配合这个规则,似乎更优雅 😄

**Comment by Mrered** [comment]
这样还有一个麻烦，有的服务必须走特殊的代理，比如 OpenAI 的流量走 Azure 机器就不会拒绝访问，走其他机器就可能不行。

**Comment by black-pwq** [comment]
> 谢谢您的解答，但我还是有一个问题，为什么要在规则集里设置直连的规则？ 那些域名既然可以直连，那就说明不包含敏感内容，那就不怕DNS泄漏，直接用 GEOIP,CN,DIRECT 概括了不就好了？

这样会造成最严重的DNS泄露，因为你拿到域名的时候不知道IP地址，必然会做DNS解析。试想一下，你正在访问google.com，而你的路由规则怎么会知道他的IP地址？考虑DNS泄露不应该考虑那些ISP地址与DNS服务器地址相同的情况，恰恰是不相同的情况才会造成泄露
