### ISSUE TITLE
app.apple.com这个域名的问题

### ISSUE THREAD

**Issue by toyo2333** [Loyalsoldier/clash-rules#209]
使用了这个规则集
https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt

在路由里规则设置了direct
 - RULE-SET,apple,DIRECT
并排在前面。但就是无法访问：
https://apps.apple.com/us/app/netnewswire-rss-reader/id1480640210

注释掉这个规则direct规则就能访问。

我看了apple.txt里由这个，相当于没有效果。但规则中的其他域名我挑了测试是有效果的比如store.apple.com
  - '+.apps.apple.com'

 以下是完整的配置
  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

rules:
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,ad2ban,REJECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,telegram,Proxy
  - RULE-SET,openai,Proxy
  - RULE-SET,direct,DIRECT
  - GEOIP,LAN,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,Proxy

客户端是Clash Verge，meta内核。

**Comment by Loyalsoldier** [comment]
那就设置为代理好了
