### ISSUE TITLE
cdn.jsdelivr.net不挂梯子访问不了。。

### ISSUE THREAD

**Issue by dagundejuzi** [Loyalsoldier/clash-rules#210]
规则的地址在浏览器无法访问，挂了梯子才能看到。
而clash软件一打开就会提示初始化错误。
<img width="262" alt="截屏2023-08-22 02 07 16" src="https://github.com/Loyalsoldier/clash-rules/assets/16382880/6b658b32-51d8-446b-ac8d-e05278dcbd7a">

**Comment by Loyalsoldier** [comment]
尝试把域名 cdn.jsdelivr.net 换成 testingcf.jsdelivr.net

**Comment by dagundejuzi** [comment]
> 尝试把域名 cdn.jsdelivr.net 换成 testingcf.jsdelivr.net

这个可以，谢谢。
