### ISSUE TITLE
能否生成text格式的规则？

### ISSUE THREAD

**Issue by PingZi-Wing** [Loyalsoldier/clash-rules#213]
text格式相比yaml更加高效，大佬能搞一下吗？参考链接：https://dreamacro.github.io/clash/zh_CN/premium/rule-providers.html

**Comment by Loyalsoldier** [comment]
「text 格式相比 yaml 更加高效」有测试数据？

**Comment by PingZi-Wing** [comment]
> 「text 格式相比 yaml 更加高效」有测试数据？

抱歉没有测试数据，记得clash作者说过一次（上万的规则能体现优势）忘记出处了，高效说法另外一个来源：https://lancellc.gitbook.io/clash/clash-config-file/rule-provider

**Comment by Loyalsoldier** [comment]
期待项目重构吧。
