### ISSUE TITLE
proxy 和 direct 规则集bug

### ISSUE THREAD

**Issue by dcty** [Loyalsoldier/clash-rules#216]
#### 白名单模式 Rules 配置方式（推荐）
`- RULE-SET,proxy,PROXY`
`- RULE-SET,direct,DIRECT`
在 https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt 中有一条规则 ` - '+.tv'`
这条规则会导致所有 `.tv` 域名都走代理
比如 https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt 中的 `  - '+.gitv.tv'
`

**Comment by Loyalsoldier** [comment]
请自行在 `- RULE-SET,proxy,PROXY` 上面（前面）添加规则
