### ISSUE TITLE
Cannot access Google Drive and Doc using Whitelist rules

### ISSUE THREAD

**Issue by XinyuZeng** [Loyalsoldier/clash-rules#217]
This only happened in the recent week. Some elements in the sites of Google Drive and Doc cannot be loaded.

Changing `  - RULE-SET,google,DIRECT` to `  - RULE-SET,google,PROXY` solves this issue.

But why google ruleset is set to DIRECT in the first place?

**Comment by Loyalsoldier** [comment]
The `google` ruleset includes Google domains that are accessible in China mainland. It comes from upstream repo: https://github.com/felixonmars/dnsmasq-china-list/blob/master/google.china.conf
