### ISSUE TITLE
gstatic.com相关域名不应该在direct规则集里

### ISSUE THREAD

**Issue by Ricardo-Evans** [Loyalsoldier/clash-rules#222]
gstatic.com在大陆部分地区（如上海）会出现间歇性的不可用，使用直连规则导致部分网页，如google账号登陆界面、微软主页等，出现脚本加载不全完全无法使用的问题

**Comment by Loyalsoldier** [comment]
那么建议把相关 Google 域名设置为代理，自行处理

**Comment by chia4** [comment]
还有.googleapis.com也是

**Comment by watchingfun** [comment]
有点逆天了，大家为啥用规则集，不就是为了省心不想自己配置规则吗，结果把谷歌的相关服务域名放到直连规则列表
