### ISSUE TITLE
BitComet_x64.exe 需要加入到 applications.txt 中

### ISSUE THREAD

**Issue by Magic989** [Loyalsoldier/clash-rules#225]
![1](https://p.sda1.dev/13/15d626365c8e74cbd163510466fb87af/image.png)

**Comment by Vulcankta** [comment]
附議

**Comment by Loyalsoldier** [comment]
Windows 系统下还有别的奇怪的进程名称需要添加吗？

**Comment by Vulcankta** [comment]
- PROCESS-NAME,DownloadSDKServer.exe
 - PROCESS-NAME,AntDM.exe
 - PROCESS-NAME,AnyDesk.exe
 - PROCESS-NAME,SunloginClient.exe

**Comment by Magic989** [comment]
> Windows 系统下还有别的奇怪的进程名称需要添加吗？

大佬抱歉啊，确实是很难一一列举，基本上是一些 P2P 下载器或者代理工具，遇到的频次也不高，还是交由用户自己添加吧。

**Comment by Loyalsoldier** [comment]
已添加 `DownloadSDKServer.exe` 和 `BitComet_x64.exe`
