### ISSUE TITLE
希望开一个 ChatGPT 相关的规则

### ISSUE THREAD

**Issue by jacinzhang** [Loyalsoldier/clash-rules#226]
由于 ChatGPT，香港地区的IP 被封锁，所以需要指定为非香港地区的节点，
这部分需要自定义配置，
所以，希望出一个 ChatGPT 的规则集，可以直接配置。
ChatGPT 规则集可以参考 
https://raw.githubusercontent.com/wlxuf/add_rule/main/ChatGPT.list

**Comment by Loyalsoldier** [comment]
等待项目重构吧。或者先自行添加到规则中

**Comment by psychopasss** [comment]
> 等待项目重构吧。或者先自行添加到规则中

啥时候重构啊，geosite太庞大了，而且在各个平台的兼容性也不好，还是rule-set靠谱点。
