### ISSUE TITLE
黑名单下，www.naver.com 使用了直连，使用  - DOMAIN,naver.com,PROXY  自定义规则也无法生效

### ISSUE THREAD

**Issue by gosip443** [Loyalsoldier/clash-rules#227]
INF [TCP] connected lAddr=127.0.0.1:55047 rAddr=www.naver.com:443 mode=rule rule=Match() proxy=DIRECT

**Comment by Loyalsoldier** [comment]
应该使用 `DOMAIN-SUFFIX`。

DOMAIN-SUFFIX,naver.com,PROXY
