### ISSUE TITLE
小白想问一下

### ISSUE THREAD

**Issue by HaiBingmo** [Loyalsoldier/clash-rules#233]
- RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
 的规则列表和
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
 的规则列表有什么区别吗，重复匹配会不会降低效率？

**Comment by Loyalsoldier** [comment]
GEOIP 的规则可以添加 `,no-resolve`，以此避免 DNS 泄漏，但需要手动更新 GEOIP 数据库文件。
RULE-SET 规则可以自动更新，但不能添加 `,no-resolve`。需要配合 fakeip 才能避免 DNS 泄漏。

两种不需要同时使用。

**Comment by HaiBingmo** [comment]
哦，谢谢～
