### ISSUE TITLE
建议添加*.nih.gov到直连列表

### ISSUE THREAD

**Issue by sun-jiao** [Loyalsoldier/clash-rules#235]
这个网站是美国卫生研究院的，属于美国国有的科研机构，虽然是美国政府的gov顶级域但是没有被墙。而且这个网站如果挂代理反而大概率进不去（疑似屏蔽了主要的云服务器厂商）。

**Comment by Loyalsoldier** [comment]
请自行添加规则。

**Comment by sun-jiao** [comment]
我自己加了。但是你这儿加上不是所有人都能用吗。
