### ISSUE TITLE
bpapi.apple.com需要直连

### ISSUE THREAD

**Issue by aes256ctr** [Loyalsoldier/clash-rules#237]
`bpapi.apple.com`如果走代理的话，会导致iPhone不能获取OS更新
请添加到apple DIRECT规则集

**Comment by Loyalsoldier** [comment]
根据 https://support.apple.com/zh-cn/HT210060 ，域名 `bpapi.apple.com` 支持使用代理

**Comment by aes256ctr** [comment]
但是我昨天在两个不同型号的iPhone测试了（IOS 17.1.1-->17.1.2 ），开启代理的情况下，确实会报错，并且无法获取更新。
请您测试。
