### ISSUE TITLE
为什么将v2ray等设置为DIRECT

### ISSUE THREAD

**Issue by eastarpen** [Loyalsoldier/clash-rules#24]
如题, rules 中PROCESS-NAME大量的DIRECT， 不太明白用意

**Comment by Loyalsoldier** [comment]
将那些软件都设置为直连，有些是代理软件，有些是下载软件。

**Comment by eastarpen** [comment]
> 将那些软件都设置为直连，有些是代理软件，有些是下载软件。

如果将其他代理软件按clash规则代理是会引发什么问题？（其他代理无效？clash无法正常工作？...）
你的rule-providers中有些链接过期，如果直接粘贴只有gfw能正常下载规则文件
（20210401，windows
 10， cfw）

**Comment by eastarpen** [comment]
![Uploading rule-set_apple.jpg…]()

**Comment by Loyalsoldier** [comment]
网络流量被二次处理或者陷入死循环。已确认链接没问题。
