### ISSUE TITLE
Clash premium 的 proxy-providers 功能文档地址打不开了，有保留的文档吗

### ISSUE THREAD

**Issue by zhaopanlong** [Loyalsoldier/clash-rules#241]
Clash premium 的 proxy-providers 功能：https://github.com/Dreamacro/clash/wiki/Configuration#proxy-providers  地址打不开了

**Comment by zhaopanlong** [comment]
我是小白 现在就是想添加自定义规则，并且在更新订阅的时候还在，通过proxy-providers可以操作 有具体的文档吗

**Comment by Loyalsoldier** [comment]
参考这个配置文件：https://github.com/Loyalsoldier/clash-rules/blob/hidden/config.yaml

**Comment by zhaopanlong** [comment]
如何订阅地址是base64文件怎么处理

**Comment by zhaopanlong** [comment]
> 参考这个配置文件：https://github.com/Loyalsoldier/clash-rules/blob/hidden/config.yaml

如何订阅地址是base64文件怎么处理

**Comment by Loyalsoldier** [comment]
将配置文件转换为 Clash 支持的格式：https://github.com/tindy2013/subconverter

**Comment by QZLin** [comment]
https://web.archive.org/web/20230315170632/https://lancellc.gitbook.io/clash/
