### ISSUE TITLE
clash v0.20.39使用报错

### ISSUE THREAD

**Issue by AliceNEET** [Loyalsoldier/clash-rules#242]
通过查看日志，发现了一个错误导致无法连接clash core

17:36:22 FTL [Config] parse config failed error=rules[8] [RULE-SET,proxy,PROXY] error: proxy [PROXY] not found

这个是啥原因？

**Comment by Loyalsoldier** [comment]
要在 `proxies` 或 `proxy-groups` 中创建一个 `name` 为 `PROXY` 的代理，参考：https://github.com/Loyalsoldier/clash-rules/blob/b2231564b01fa6fa1ae9456b12bdf05c3d86a4ee/config.yaml#L55-L64
