### ISSUE TITLE
提一个可能是内核bug导致的问题

### ISSUE THREAD

**Issue by JoJenH** [Loyalsoldier/clash-rules#246]
规则集过长的话，后面的规则可能匹配不到。proxy集里面有关于Steam的steampower的一条规则，大概在两万五千行左右，我的配置里这个规则集是走国外流量，但是实际使用过程中发现会匹配不到，最终认为是无匹配。二分尝试了其它域名，前面的基本都能正常匹配，这条后面的都匹配不到了，猜测可能是规则集长度的问题。尝试了几个不同客户端，都存在这样的问题，那么bug可能就在内核了。我个人水平有限，后续您这边可以再实验核实一下，如果是这样的话，可能建议您这边对规则集进行一下拆分，比如proxy1和proxy2这样。

**Comment by Loyalsoldier** [comment]
无法复现。

**Comment by JoJenH** [comment]
确定是个人配置的问题，给您添麻烦了。顺便想请问一下，这个项目预计什么时候重构，重构的重点大概在哪些方面？
