### ISSUE TITLE
白名单模式包含direct规则后googledrive故障

### ISSUE THREAD

**Issue by toyo2333** [Loyalsoldier/clash-rules#248]
经过我反复测试
白名单规则策略，使用direct规则的走直连

- RULE-SET,direct,DIRECT

这个时候打开谷歌硬盘https://drive.google.com/ 会出现一个故障

可以打开页面，并加载数据，但是大概10秒钟后，内容列表就变灰，这个时候点任何一个内容（比如照片、文档什么的）都提示“无法在离线状态下开启这些项目”

我反复测试，用全局模式正常 or 规则里移除direct后也正常。

请确认是否存在不合理的规则导致的?

感谢。

**Comment by Loyalsoldier** [comment]
将本项目中的 Google 域名列表设置为代理，应该可以解决
