### ISSUE TITLE
Telegram地址有更新 

### ISSUE THREAD

**Issue by Android-AwesomeRoy** [Loyalsoldier/clash-rules#252]
https://[core.telegram.org/resources/cidr.txt](https://core.telegram.org/resources/cidr.txt)

91.108.56.0/22
91.108.4.0/22
91.108.8.0/22
91.108.16.0/22
91.108.12.0/22
149.154.160.0/20
91.105.192.0/23
91.108.20.0/22
185.76.151.0/24
2001:b28:f23d::/48
2001:b28:f23f::/48
2001:67c:4e8::/48
2001:b28:f23c::/48
2a0a:f280::/32

**Comment by Loyalsoldier** [comment]
本项目会自动更新的

**Comment by Android-AwesomeRoy** [comment]
> 本项目会自动更新的

并没有自动更新，你可以看一下最近提交的和readme里的链接，没有变化。

**Comment by Loyalsoldier** [comment]
数量看着不对，是因为 CIDR 被合并了
