### ISSUE TITLE
GooglePlay应用商店无法更新, 需要添加一条规则

### ISSUE THREAD

**Issue by ooeooo** [Loyalsoldier/clash-rules#253]
- DOMAIN-SUFFIX,xn--ngstr-lra8j.com,Proxy
  - DOMAIN-SUFFIX,services.googleapis.cn,Proxy

GooglePlay商店更新应用时一直处于等待中, 原因是上面的两个网址不在代理列表中, 烦请将其添加到google代理名单中

**Comment by Loyalsoldier** [comment]
感谢提醒，建议自行添加规则
