### ISSUE TITLE
谷歌服务好像有点问题

### ISSUE THREAD

**Issue by shentong0722** [Loyalsoldier/clash-rules#256]
大概两个星期前出现的，很多谷歌服务没有走代理导致出现很多问题
比如reCAPTURE等
切换全局代理就好了，因此确认是分流规则出现问题

**Comment by shentong0722** [comment]
好像是：
![image](https://github.com/Loyalsoldier/clash-rules/assets/63089521/ed88d697-0d8c-4821-ab6a-04b560d30a6e)
google怎么会走DIRECT呢？

**Comment by Turingrun** [comment]
[慎用]Google 在中国大陆可直连的域名列表 google.txt：

这条规则直接弃用吧。

**Comment by Loyalsoldier** [comment]
白名单模式中已默认不使用 google 列表：https://github.com/Loyalsoldier/clash-rules/commit/9a9da56903441c32daf6848388f65cf17ea4603f
