### ISSUE TITLE
如何使用呀？

### ISSUE THREAD

**Issue by 11003** [Loyalsoldier/clash-rules#257]
> 要想使用本项目的规则集，只需要在 Clash 配置文件中添加如下 rule-providers 和 rules

意思是新建文件吗？
![image](https://github.com/Loyalsoldier/clash-rules/assets/35055270/efe6fb2f-d05e-4659-b0de-59d4b957f4c8)

**Comment by 1523789353** [comment]
选中你使用的订阅，右键编辑，添加rule-providers/rules
![image](https://github.com/Loyalsoldier/clash-rules/assets/39769643/72e135af-32c3-4244-ab7c-a676611259a3)
![image](https://github.com/Loyalsoldier/clash-rules/assets/39769643/13d47382-3af6-4b1d-ace8-37b98441d947)

**Comment by 11003** [comment]
谢谢大佬

**Comment by Kukuair** [comment]
> 选中你使用的订阅，右键编辑，添加rule-providers/rules ![image](https://private-user-images.githubusercontent.com/39769643/300279584-72e135af-32c3-4244-ab7c-a676611259a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDM2MTEsIm5iZiI6MTcxMjY0MzMxMSwicGF0aCI6Ii8zOTc2OTY0My8zMDAyNzk1ODQtNzJlMTM1YWYtMzJjMy00MjQ0LWFiN2MtYTY3NjYxMTI1OWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2MTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NTBkMzEyYTA3NWQ2NGU5YzY5MDAyNGYwMjg3NTIzMzZlMjlhYTU2ZDQ3OGMxMzhmOWM5MjgzYTA0MWQyNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K-u5uB57ugVw34NJ3npqlcL2jvH6qcD97e4kQRBbprA) ![image](https://private-user-images.githubusercontent.com/39769643/300279742-13d47382-3af6-4b1d-ace8-37b98441d947.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDM2MTEsIm5iZiI6MTcxMjY0MzMxMSwicGF0aCI6Ii8zOTc2OTY0My8zMDAyNzk3NDItMTNkNDczODItM2FmNi00YjFkLWFjZTgtMzdiOTg0NDFkOTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2MTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMzA1YjkzYTkyOTAyNzBhNWQzMzllODI3YTNlMjg5M2JlYjc4MmQyNzhmZDQzNWNhZWI1MjhmMjZjMjFkYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.miOizTqumzUgS5CTlKFrHQiDieX8gYZ9fe-ZGxnqGHQ)

刚接触clashN，之前用的v2rayN , 我有个问题就是一般机场的clash的订阅都是yaml格式的文件，然后节点和规则都在这个yaml里，那如果开启的自动更新订阅后，那岂不是每次都要手动改yaml？

**Comment by sanwacompany** [comment]
> > 选中你使用的订阅，右键编辑，添加rule-providers/rules ![image](https://private-user-images.githubusercontent.com/39769643/300279584-72e135af-32c3-4244-ab7c-a676611259a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDM2MTEsIm5iZiI6MTcxMjY0MzMxMSwicGF0aCI6Ii8zOTc2OTY0My8zMDAyNzk1ODQtNzJlMTM1YWYtMzJjMy00MjQ0LWFiN2MtYTY3NjYxMTI1OWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2MTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NTBkMzEyYTA3NWQ2NGU5YzY5MDAyNGYwMjg3NTIzMzZlMjlhYTU2ZDQ3OGMxMzhmOWM5MjgzYTA0MWQyNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K-u5uB57ugVw34NJ3npqlcL2jvH6qcD97e4kQRBbprA) ![image](https://private-user-images.githubusercontent.com/39769643/300279742-13d47382-3af6-4b1d-ace8-37b98441d947.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDM2MTEsIm5iZiI6MTcxMjY0MzMxMSwicGF0aCI6Ii8zOTc2OTY0My8zMDAyNzk3NDItMTNkNDczODItM2FmNi00YjFkLWFjZTgtMzdiOTg0NDFkOTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2MTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMzA1YjkzYTkyOTAyNzBhNWQzMzllODI3YTNlMjg5M2JlYjc4MmQyNzhmZDQzNWNhZWI1MjhmMjZjMjFkYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.miOizTqumzUgS5CTlKFrHQiDieX8gYZ9fe-ZGxnqGHQ)
> 
> 刚接触clashN，之前用的v2rayN , 我有个问题就是一般机场的clash的订阅都是yaml格式的文件，然后节点和规则都在这个yaml里，那如果开启的自动更新订阅后，那岂不是每次都要手动改yaml？

我也有相同的疑问😂

**Comment by Kukuair** [comment]
> > > 选中你使用的订阅，右键编辑，添加rule-providers/rules ![image](https://private-user-images.githubusercontent.com/39769643/300279584-72e135af-32c3-4244-ab7c-a676611259a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDM2MTEsIm5iZiI6MTcxMjY0MzMxMSwicGF0aCI6Ii8zOTc2OTY0My8zMDAyNzk1ODQtNzJlMTM1YWYtMzJjMy00MjQ0LWFiN2MtYTY3NjYxMTI1OWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2MTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NTBkMzEyYTA3NWQ2NGU5YzY5MDAyNGYwMjg3NTIzMzZlMjlhYTU2ZDQ3OGMxMzhmOWM5MjgzYTA0MWQyNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K-u5uB57ugVw34NJ3npqlcL2jvH6qcD97e4kQRBbprA) ![image](https://private-user-images.githubusercontent.com/39769643/300279742-13d47382-3af6-4b1d-ace8-37b98441d947.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDM2MTEsIm5iZiI6MTcxMjY0MzMxMSwicGF0aCI6Ii8zOTc2OTY0My8zMDAyNzk3NDItMTNkNDczODItM2FmNi00YjFkLWFjZTgtMzdiOTg0NDFkOTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2MTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMzA1YjkzYTkyOTAyNzBhNWQzMzllODI3YTNlMjg5M2JlYjc4MmQyNzhmZDQzNWNhZWI1MjhmMjZjMjFkYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.miOizTqumzUgS5CTlKFrHQiDieX8gYZ9fe-ZGxnqGHQ)
> > 
> > 
> > 刚接触clashN，之前用的v2rayN , 我有个问题就是一般机场的clash的订阅都是yaml格式的文件，然后节点和规则都在这个yaml里，那如果开启的自动更新订阅后，那岂不是每次都要手动改yaml？
> 
> 我也有相同的疑问😂

https://github.com/Loyalsoldier/clash-rules/issues/260#issuecomment-2044285349
