### ISSUE TITLE
中国区Apple Map的相关域名被代理导致一系列问题

### ISSUE THREAD

**Issue by Turingrun** [Loyalsoldier/clash-rules#259]
由于Apple地图的相关域名未被收录，故命中proxy走了代理导致在国内无法使用Apple地图进行路线导航等功能。
日志如下：
`
[TCP] 192.168.1.156:51451 --> gsp64-ssl.ls.apple.com:443 match RuleSet(proxy) using PROXY[🇭🇰 [v1] 香港・08]

[TCP] 192.168.1.217:6796 --> gsp-ssl.ls.apple.com:443 match RuleSet(proxy) using PROXY[🇭🇰 [v1] 香港・08]

[TCP] 192.168.1.217:6797 --> gsp-ssl.ls.apple.com:443 match RuleSet(proxy) using PROXY[🇭🇰 [v1] 香港・08]

[TCP] 192.168.1.156:51393 --> gspe12-ssl.ls.apple.com:443 match RuleSet(proxy) using PROXY[🇭🇰 [v1] 香港・08]`

目前寻找到了一种可行的解决方案: @https://github.com/kivvi3412/Mainland_China_Rules_List  希望可以将这些域名收录进rules-provider下的apple.txt

**Comment by Loyalsoldier** [comment]
建议到上游项目提 issue：https://github.com/felixonmars/dnsmasq-china-list
