### ISSUE TITLE
小白求教具体使用方法

### ISSUE THREAD

**Issue by xlfq3136** [Loyalsoldier/clash-rules#260]
找了一会子，还是不大会用，希望大大出个小白教程。

**Comment by Loyalsoldier** [comment]
用什么操作系统？

**Comment by xxxxue** [comment]
相同的issues 
https://github.com/Loyalsoldier/clash-rules/issues/257#issuecomment-1913659972

**Comment by Kukuair** [comment]
刚接触clashN，之前用的v2rayN , 我有个问题就是一般机场的clash的订阅都是yaml格式的文件，然后节点和规则都在这个yaml里，那如果开启的自动更新订阅后，那岂不是每次都要手动改yaml？

**Comment by Loyalsoldier** [comment]
自己写一个配置文件，将机场提供的配置文件作为 proxy-provider 使用，参考：https://github.com/Loyalsoldier/clash-rules/blob/hidden/config.yaml

**Comment by Kukuair** [comment]
> 自己写一个配置文件，将机场提供的配置文件作为 proxy-provider 使用，参考：https://github.com/Loyalsoldier/clash-rules/blob/hidden/config.yaml

我试了一下，发现个问题，我如果关闭并退出代理软件，直接访问 https://ipw.cn/ ，网站会提示是ipv6优先访问（本地运营商的ip），但是如果打开代理，选择  全局模式   选中节点，再次访问，同样也是会提示是ipv6优先访问（节点也有ipv6），但是当我选择  规则模式   后再再次访问，就会显示ipv4优先访问，但是ipv6也是显示是有地址的，为啥选择  规则模式   后就是 ipv4优先访问了呢？ 请问您知道这是什么原因吗？
