### ISSUE TITLE
一些Url能够实现流量剩余显示，有相关文档提及是如何在cfw的UI上实现的吗？

### ISSUE THREAD

**Issue by galaxysmonkey** [Loyalsoldier/clash-rules#265]

**Comment by Loyalsoldier** [comment]
不太清楚

**Comment by NXY666** [comment]
![image](https://github.com/Loyalsoldier/clash-rules/assets/62371554/d7fed136-15a2-48bb-9fd2-1ce45fb7f6ae)
请求响应头
