### ISSUE TITLE
google play 下载失败

### ISSUE THREAD

**Issue by GetStart13** [Loyalsoldier/clash-rules#266]
某些谷歌服务走了直连，导致能进谷歌商店和浏览内容，但是下载一直转圈，我在规则列表顶级代理掉谷歌才恢复正常

**Comment by NXY666** [comment]
> 感谢提醒。README 里的规则已经默认代理 Google 相关服务

似乎还是不行，我对比了一下日志（和其他机场的规则），可能是connectivitycheck.gstatic.com走直连导致的，它在private列表中。

**Comment by GetStart13** [comment]
> > 感谢提醒。README 里的规则已经默认代理 Google 相关服务
> 
> 似乎还是不行，我对比了一下日志（和其他机场的规则），可能是connectivitycheck.gstatic.com走直连导致的，它在private列表中。

应该不是，我把google关键字代理掉就可以正常访问，搜索关键字把所有直连的google关键字删掉就行，不必要走直连

**Comment by NXY666** [comment]
> 应该不是，我把google关键字代理掉就可以正常访问，搜索关键字把所有直连的google关键字删掉就行，不必走直连

草，那看起来是services.googleapis.cn，.cn直接走直连了。

**Comment by GetStart13** [comment]
> > 应该不是，我把google关键字代理掉就可以正常访问，搜索关键字把所有直连的google关键字删掉就行，不必走直连
> 
> 草，那看起来是services.googleapis.cn，.cn直接走直连了。

哈哈哈，我也草了，我在排查qq的游戏推送的链接，想屏蔽掉它，qq新版本(nt架构版本)的广告比较少，但是侧边栏有个游戏图标，tx这尿性不给隐藏这图标，老是弹一个消息提示，我要把这些推送禁完，但好像它的域名不止一个，调试了我两天…
