### ISSUE TITLE
是否支持subconverter的config

### ISSUE THREAD

**Issue by hoshibara** [Loyalsoldier/clash-rules#268]
如题，不知该repo是否有支持[subconverter](https://github.com/tindy2013/subconverter) config的方法？
就像[这样](https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/config/ACL4SSR_Online.ini)。

**Comment by Loyalsoldier** [comment]
看了一下，应该可以用于 subconverter 中的 ruleset
