### ISSUE TITLE
广告规则误杀了 android 开发的 maven 仓库域名

### ISSUE THREAD

**Issue by julee** [Loyalsoldier/clash-rules#270]
Loyalsoldier/clash-rules/release/reject.txt  规则中，包含了  - '+.fabric.io' ，但是 maven.fabric.io 是一个正常的 maven 仓库，放的是 android 和 java 开发需要的包。 

仓库被误杀，造成广告规则设置成 reject 时，android 构建因无法访问在线仓库而失败。

**Comment by Loyalsoldier** [comment]
感谢反馈，已在上游项目中处理 https://github.com/Loyalsoldier/v2ray-rules-dat/commit/4d66f447fdd903734d761a247c6682a9fd2796d1
