### ISSUE TITLE
services.googleapis.cn直连导致GooglePlay无法下载

### ISSUE THREAD

**Issue by NXY666** [Loyalsoldier/clash-rules#272]
经过测试，能够确认是services.googleapis.cn走直连导致的，且只有安装了较新版本的GooglePlay服务才会出现这个情况。

测试方法：通过Parser单独增加services.googleapis.cn为代理后，GooglePlay下载恢复正常。

我不太清楚在这里反馈是否正确，如果我需要去其它仓库反馈，请告知我。

**Comment by Loyalsoldier** [comment]
因为 `.cn` 顶级域名在直连列表里。

已将 `services.googleapis.cn` 添加到代理列表，见：https://github.com/Loyalsoldier/v2ray-rules-dat/commit/e2306ea1ef3d6b017a2e3461ee6af32632c68de0

**Comment by NXY666** [comment]
> 因为 `.cn` 顶级域名在直连列表里。
> 
> 已将 `services.googleapis.cn` 添加到代理列表，见：[Loyalsoldier/v2ray-rules-dat@e2306ea](https://github.com/Loyalsoldier/v2ray-rules-dat/commit/e2306ea1ef3d6b017a2e3461ee6af32632c68de0)

有点奇怪，v2ray-rules-dat已经发布了多个版本，但是services.googleapis.cn始终没有出现在它的代理列表中，不知道是哪里出现了问题？
