### ISSUE TITLE
dcg.microsoft.com需要直连

### ISSUE THREAD

**Issue by NXY666** [Loyalsoldier/clash-rules#273]
如果国产手机内置了微软的“链接到windows”，一旦“dcg.microsoft.com”使用代理，功能就会立刻被禁用。

详见：https://answers.microsoft.com/zh-hans/windows/forum/all/%E6%97%A0%E6%B3%95%E8%BF%9E%E6%8E%A5%E5%88%B0/c4e02382-f779-43fe-b66b-2685daacf67a

我也被禁用过 :(

因此这个域名应走直连。

对了，还有个疑问，如果是一些比较小众的网站（比如说一些个人网站），可以申请走直连吗？还是说它的收录有什么要求？

**Comment by Loyalsoldier** [comment]
已处理，见：https://github.com/v2fly/domain-list-community/pull/2105

本项目的上游项目是 https://github.com/v2fly/domain-list-community ，可到那提 issue。

**Comment by NXY666** [comment]
> 本项目的上游项目是 https://github.com/v2fly/domain-list-community ，可到那提 issue。

好的。
