### ISSUE TITLE
windows 11 ``Copliot`` 无法连接到服务器

### ISSUE THREAD

**Issue by oooplz** [Loyalsoldier/clash-rules#276]
windows 11 ``Copliot`` 无法连接到服务器

**Comment by Loyalsoldier** [comment]
有什么错误提示吗？

**Comment by oooplz** [comment]
感谢你的回复。没有什么错误提示，我是用Windows11系统自带的 ``Copilot`` 和 EDGE 的 ``Copilot``，一直处于"任在加载中"，30秒钟左右提示无法连接....

**Comment by oooplz** [comment]
``很抱歉，目前无法连接到服务。``

**Comment by Loyalsoldier** [comment]
参考：https://answers.microsoft.com/zh-hans/insider/forum/all/%E4%B8%AD%E5%9B%BD%E5%A4%A7%E9%99%86%E5%9C%B0/a32c65dc-2807-419b-8b4c-f6e832c634c2
