### ISSUE TITLE
怎么解决clash for windows中的配置定时Update Interval后覆盖已配置好的规则？

### ISSUE THREAD

**Issue by Wang-Zhengkang** [Loyalsoldier/clash-rules#277]

**Comment by Loyalsoldier** [comment]
在本地创建一个配置文件，通过 `proxy-providers` 的方式引入服务提供商的配置文件，参考：https://github.com/Loyalsoldier/clash-rules/blob/hidden/config.yaml

**Comment by Wang-Zhengkang** [comment]
你好，按照你说的方式下载了config.yaml文件，将配置文件中的url地址替换为了机场订阅链接，报错如下图所示。
![Snipaste_2024-04-16_11-07-02](https://github.com/Loyalsoldier/clash-rules/assets/117054885/cb6a5735-9dce-43ff-bb78-ffda5f0898bd)

**Comment by Wang-Zhengkang** [comment]
> 在本地创建一个配置文件，通过 `proxy-providers` 的方式引入服务提供商的配置文件，参考：https://github.com/Loyalsoldier/clash-rules/blob/hidden/config.yaml

你好，按照你说的方式下载了config.yaml文件，将配置文件中的url地址替换为了机场订阅链接，报错如下图所示。
![Snipaste_2024-04-16_11-07-02](https://github.com/Loyalsoldier/clash-rules/assets/117054885/5e0d29e5-0a77-4408-9aa2-8339e3af3099)

**Comment by Loyalsoldier** [comment]
机场订阅需要支持 Clash。如果不支持，可以转换：https://github.com/tindy2013/subconverter

**Comment by Black-To-Hand** [comment]
可以通过更改Diff

**Comment by Wang-Zhengkang** [comment]
> 可以通过更改Diff

牛皮兄弟，成功解决！
