### ISSUE TITLE
一点小看法

### ISSUE THREAD

**Issue by NXY666** [Loyalsoldier/clash-rules#279]
一些比较大的网站，比如说Google、Microsoft，它们有非常多的域名，可能有的应该走直连，有的有应该走代理。

但是存在一些比较激进（？）一点的规则，比如说'+.microsoft.com'、'+.cn'，它们似乎比较容易出现误判，因为它们的优先级不够低。

比如说我之前提到的dcg.microsoft.com，要让它走直连，就必须把direct放在proxy之前，但是这样做后，service.googleapis.cn又会因为'+.cn'被走直连，不知道有没有可能把这些比较模糊的规则（比如说规则中.的数量＜3的？）分离出来，排在普通的proxy和direct后面？

但是可能实现起来会比较麻烦。

或者还有什么办法能解决这种优先级问题吗？

**Comment by Loyalsoldier** [comment]
想要精确结果，就用 DNS 对每个域名进行解析。域名规则没法做到这么细致

**Comment by NXY666** [comment]
> 想要精确结果，就用 DNS 对每个域名进行解析。域名规则没法做到这么细致

它的尴尬之处就在这，有些服务不能完全根据解析出的ip选择代理。

比如说dcg.microsoft.com解析出来的IP地址在美国，但是它必须走直连。

services.googleapis.cn解析的IP地址在北京，但是走直连Google Play就无法下载😶

如果是大的国际公司，这种例外就格外常见😂
