### ISSUE TITLE
关于clash订阅更新覆盖配置问题

### ISSUE THREAD

**Issue by luziyi** [Loyalsoldier/clash-rules#280]
subscribe?token=cc3aec52ca2daw2dasda8c1e812e9a110

我的订阅连接是这样的，应该怎么样防止订阅后覆盖规则呢？

**Comment by Loyalsoldier** [comment]
自己新建一个配置文件，通过 `proxy-providers` 添加订阅，参考 https://github.com/Loyalsoldier/clash-rules/blob/hidden/config.yaml
