### ISSUE TITLE
规则的重复

### ISSUE THREAD

**Issue by ky0utarou** [Loyalsoldier/clash-rules#281]
部分规则中存在重复条目，例如https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt 中存在若干`adobe`的完全匹配规则
``` 
  - '3dns-1.adobe.com'
  - '3dns-2.adobe.com'
  - '3dns-3.adobe.com'
  - '3dns-4.adobe.com'
  - '3dns-5.adobe.com'
  - '3dns.adobe.com'
```
又同时存在`- '+.adobe.com'`能涵盖包括上面所有子域名的通配符规则。也就是说在同一规则集中存在能涵盖其他条目的条目，那么覆盖范围更小的条目是否有存在的必要？

**Comment by Loyalsoldier** [comment]
感谢提醒
