### ISSUE TITLE
请求添加对小米应用商店的规则

### ISSUE THREAD

**Issue by THR-hub** [Loyalsoldier/clash-rules#282]
不管白名单还是黑名单，从小米应用商店下载应用都会被分流到代理上导致浪费流量，用clash for android的日志分析不出用的是哪个域名/ip。另外黑名单会导致无法下载，重复点击几次下载按钮才能下载（可能与fake-ip有关）。

**Comment by Loyalsoldier** [comment]
没有小米手机，不好复现问题
