### ISSUE TITLE
延迟测速全部失败，但访问网络正常

### ISSUE THREAD

**Issue by sanwacompany** [Loyalsoldier/clash-rules#283]
![WX20240523-131459@2x](https://github.com/Loyalsoldier/clash-rules/assets/88942504/979175e6-5516-481a-b7e6-81adf7006102)

参考了“参考 https://github.com/Loyalsoldier/clash-rules/blob/hidden/config.yaml”做的配置文件，可以成功更新，也可以正常访问外网，但延迟测速全部失败，请问该如何处理？

**Comment by Loyalsoldier** [comment]
我也不知道

**Comment by awaken233** [comment]
存在相同问题, 蹲一个解决方案
