### ISSUE TITLE
因为 opanai 的关系，很多域名走代理都需要区分国家

### ISSUE THREAD

**Issue by wujun4code** [Loyalsoldier/clash-rules#285]
例如 openai/claude2 等都是屏蔽香港节点，因此需要把 openai 从 proxy 组里面拆出来，目的是针对这些域名单独可以配一个规则，proxy 组大多数都是香港可以访问的。

**Comment by Loyalsoldier** [comment]
在配置文件中的 proxy 上面（前面）添加你需要的规则即可。
