### ISSUE TITLE
boihek.com这个网站是国内的，但是走的代理

### ISSUE THREAD

**Issue by facebook20146** [Loyalsoldier/clash-rules#289]
家里老人看直播，打不开，我看了下域名为boihek.com，用域名查询为腾讯云的IP，49.232.167.13，北京，腾讯云
大佬能加进去吗，直连列表
或者更简单的方式

**Comment by frankykoalo** [comment]
rules里手动加一条就行了吧：
  - 'DOMAIN-SUFFIX,boihek.com,DIRECT'

**Comment by facebook20146** [comment]
> rules里手动加一条就行了吧：
> 
> * 'DOMAIN-SUFFIX,boihek.com,DIRECT'

怎么向geosite提交这个网站，帮助
geosite完善😃

**Comment by Loyalsoldier** [comment]
@facebook20146  https://github.com/v2fly/domain-list-community

**Comment by facebook20146** [comment]
> @facebook20146 https://github.com/v2fly/domain-list-community

谢谢
