### ISSUE TITLE
请问Proxy和GFWList+GreatFile，有何不同，需要一起使用么？

### ISSUE THREAD

**Issue by ArthurSmoke** [Loyalsoldier/clash-rules#29]
在[Loyalsoldier/v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat)没有找到ProxyList相关的解释，不是十分清楚这个List的作用。
希望能解惑，感谢

**Comment by Loyalsoldier** [comment]
GFWList 和 Greatfire 只包含被屏蔽的域名，Proxy 包括了前两者，还包含一些未被屏蔽的海外域名。
