### ISSUE TITLE
关于腾讯云的部分域名tencent-colud的匹配规则问题

### ISSUE THREAD

**Issue by langzigyq** [Loyalsoldier/clash-rules#297]
工具clash verge ，完全使用的本项目示例配置。

发现腾讯云部分国内域名走了代理。最起码这个tencent-cloud.cn，tencent-cloud.com是可以走直连的吧，其他几个不晓得。
![截图20240720132348](https://github.com/user-attachments/assets/f5067d03-9090-4df1-802f-8d5f3c19e9e4)

![截图20240720132652](https://github.com/user-attachments/assets/5c3cff8d-8ee8-40a1-870d-b95793ad0d11)

**Comment by Loyalsoldier** [comment]
已在上游项目中修复：https://github.com/v2fly/domain-list-community/pull/2255
