### ISSUE TITLE
steam下载受到影响

### ISSUE THREAD

**Issue by verity886** [Loyalsoldier/clash-rules#30]
白名单模式和黑名单模式都试了，steam下载和商店等正常可访问地址都走了代理

**Comment by Loyalsoldier** [comment]
看[这里](https://github.com/Loyalsoldier/v2ray-rules-dat#%E9%AB%98%E7%BA%A7%E7%94%A8%E6%B3%95)，自行添加一下 steam 的直连规则。

**Comment by verity886** [comment]
不好意思，链接中的v2ray配置，我不知道怎么转换成clash的，可否给出clash的规则参考

**Comment by Loyalsoldier** [comment]
```
rules:
  - DOMAIN-SUFFIX,dl.steam.ksyna.com,DIRECT
```

类似上面这样。把 steam 的直连规则放在 `- RULE-SET,proxy,PROXY` 的上（前）面
