### ISSUE TITLE
示例配置可以增加Geo配置模版吗？不需要规则集的那种

### ISSUE THREAD

**Issue by realcirno** [Loyalsoldier/clash-rules#300]
mihomo官方文档的GeoX感觉不是很好用，大佬能增加一个GeoX的配置模版吗？

**Comment by Loyalsoldier** [comment]
GeoX 其实就是 V2Ray 的 dat 格式文件，从项目 [v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat) 下载即可。配置文件参考官网：https://wiki.metacubex.one/example/conf/#__tabbed_1_1
