### ISSUE TITLE
Adguard DNS 域名拦截名单

### ISSUE THREAD

**Issue by kurdsvv** [Loyalsoldier/clash-rules#31]
Adguard (安卓广告DNS 域名拦截)原链接
https://filters.adtidy.org/android/filters/15_optimized.txt

转换链接
[https://raw.githubusercontent.com/kurdsvv/clash-rules/master/Myreject.yaml](url)

**Comment by Loyalsoldier** [comment]
`reject.txt` 已经包含了绝大部分这个列表里的域名。
