### ISSUE TITLE
每隔几秒都有这条警告： WARNING Load GeoIP rule: lan

### ISSUE THREAD

**Issue by pein0saga** [Loyalsoldier/clash-rules#310]
![image](https://github.com/user-attachments/assets/b25dfd30-270a-42a9-9f96-1881f76084d4)

似乎是无效警告，是否有办法（比如额外写规则）直接隐藏这条警告？

不知道是不是我组策略里面禁用智能多宿主名称解析的原因（为了防止DNS泄露）

“指定多宿主 DNS 客户端应跨网络优化名称解析。 通过跨所有网络发出并行的 DNS 查询、链路本地多播名称解析(LLMNR)查询、TCP/IP 上的 NetBIOS (NetBT)查询，此策略设置可提升性能。如果收到多个积极响应，则使用网络绑定顺序确定接受哪一个响应。

如果启用此策略设置，则 DNS 客户端将不执行优化。 将首先跨所有网络发出 DNS 查询。如果 DNS 查询失败，则发出 LLMNR 查询；如果 LLMNR 查询失败，则发出 NetBT 查询。

如果禁用或未配置此策略设置，则发出 DNS、LLMNR 和 NetBT 查询时将优化名称解析”

https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.DNSClient::DNS_SmartMultiHomedNameResolution&Language=zh-cn

**Comment by Loyalsoldier** [comment]
我猜是使用了 geodata-mode，但是 geoip 文件里没有 `lan`

**Comment by helllkz** [comment]
我的geodata-mode: false，用的https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat，还是报这个错误呢

**Comment by Loyalsoldier** [comment]
geoip、geosite、本项目里的 mmdb 规则文件，均没有 `LAN` 这个类别，类似的类别名为 `private`。`LAN` 是硬编码在 Clash 代码里的，不在规则文件里。所以使用本项目或我的其他项目的规则文件时，不能使用 LAN。
