### ISSUE TITLE
我是个小白，请问这样编写是不是就可以让GFWlist的网站走代理，其他直连了？

### ISSUE THREAD

**Issue by wcg928** [Loyalsoldier/clash-rules#314]
我是个小白，请问这样编写是不是就可以让GFWlist的网站走代理，其他直连了？

rule-providers:
  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400
    
#规则    
 rules:
  - RULE-SET,gfw,PROXY
  - MATCH,DIRECT

**Comment by Loyalsoldier** [comment]
是

**Comment by wcg928** [comment]
> 是

还是不行，缺少东西！
