### ISSUE TITLE
tvbox里有很多源域名

### ISSUE THREAD

**Issue by cjlhll** [Loyalsoldier/clash-rules#316]
如何让tvbox整个走直连呢？因为一个配置文件里有很多源，每个源对应一个域名。用黑名单模式可以实现，但是我习惯用白名单模式，黑名单会导致有些页面打不开或者很慢。

**Comment by Loyalsoldier** [comment]
如果是安装在安卓手机上的 app，可以将 app 设置为直连，或者使用基于 app 包名的规则。

**Comment by cjlhll** [comment]
是openwrt上呢。没法了吧。发自我的 iPhone在 2024年11月11日，18:44，Loyalsoldier ***@***.***> 写道：﻿
如果是安装在安卓手机上的 app，可以将 app 设置为直连，或者使用基于 app 包名的规则。

**Comment by Loyalsoldier** [comment]
openwrt 上的翻墙软件也可以使用基于进程名称的规则吧

**Comment by cjlhll** [comment]
> openwrt 上的翻墙软件也可以使用基于进程名称的规则吧

我查了一下，好像是不行。
