### ISSUE TITLE
Clash_for_Windows 填入参考

### ISSUE THREAD

**Issue by deanhzed** [Loyalsoldier/clash-rules#33]
Clash_for_Windows
-rule-provider 填入参考
https://lancellc.gitbook.io/clash/clash-config-file/rule-provider
-rule 填入参考
https://docs.cfw.lbyczf.com/contents/parser.html
https://zhuanlan.zhihu.com/p/336003879

以及
BitComet.exe下
BitComet_x64.exe 补充参考

**Comment by ThoundsN** [comment]
https://lancellc.gitbook.io/clash/clash-config-file/rule-provider   这个链接失效了
