### ISSUE TITLE
有关广告域名列表中的 analytics.google.com

### ISSUE THREAD

**Issue by hjthjthjt** [Loyalsoldier/clash-rules#4]
目前实际上 Google 分析的分析代码是走的 www.googletagmanager.com 域名，而 Google 分析的后台面板是访问的 analytics.google.com，如果直接屏蔽了 analytics.google.com 会导致无法访问后台面板，是否可以处理一下呢……？

**Comment by Loyalsoldier** [comment]
已在 https://github.com/Loyalsoldier/v2ray-rules-dat/commit/a302dab63626e6aaf3b62f40000bcedaf438d9aa 中修复。明天生成的列表会生效。
