### ISSUE TITLE
能否增加流媒体（Netflix _AWS）的txt 规则

### ISSUE THREAD

**Issue by GOUKI9999** [Loyalsoldier/clash-rules#41]
https://github.com/Loyalsoldier/v2ray-rules-dat 跳转而来，非常希望其中geosite:netflix的部分也能独立出来便于clash订阅，万分感激

**Comment by salzburgrujvnun** [comment]
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
