### ISSUE TITLE
安卓11，clash使用规则发现GOOGLE PLAY商店下载应用一直处于等待中，全局代理能够正常下载。

### ISSUE THREAD

**Issue by lu989898** [Loyalsoldier/clash-rules#42]
# Capture on 2021-07-25 11:11:06.252
11:11:08.766   Debug: [PKG] 172.31.255.253:35972 --> 108.177.125.188:5228 by 10213[com.google.uid.shared]
11:11:09.469    Info: [TCP] 172.31.255.253:35972 --> 108.177.125.188 match Match() using PROXY[trojan]
11:11:13.812   Debug: [PKG] 172.31.255.253:60084 --> connectivitycheck.gstatic.com:443 by 10212[com.android.vending]
11:11:14.286    Info: [TCP] 172.31.255.253:60084 --> connectivitycheck.gstatic.com match DomainSuffix(connectivitycheck.gstatic.com) using PROXY[trojan]
11:11:42.968   Debug: [PKG] 172.31.255.253:47742 --> diagmon-apigw.samsung.com.cn:443 by 1000[android.uid.system]
11:11:43.083    Info: [TCP] 172.31.255.253:47742 --> diagmon-apigw.samsung.com.cn match RuleSet(direct) using DIRECT
11:11:45.533   Debug: [PKG] 172.31.255.253:39552 --> in.appcenter.ms:443 by 10346[com.github.kr328.clash]
11:11:45.966    Info: [TCP] 172.31.255.253:39552 --> in.appcenter.ms match RuleSet(proxy) using PROXY[trojan]
11:11:50.808   Debug: [PKG] 172.31.255.253:51806 --> android.clients.google.com:443 by -1[]
11:11:51.417    Info: [UDP] 172.31.255.253:51806 --> android.clients.google.com match DomainKeyword(google) using PROXY[trojan]
11:11:52.260   Debug: [PKG] 172.31.255.253:53928 --> android.clients.google.com:443 by 10212[com.android.vending]
11:11:52.843    Info: [TCP] 172.31.255.253:53928 --> android.clients.google.com match DomainKeyword(google) using PROXY[trojan]
11:11:53.588   Debug: [PKG] 172.31.255.253:50922 --> services.googleapis.cn:443 by 10212[com.android.vending]
11:11:54.124    Info: [TCP] 172.31.255.253:50922 --> services.googleapis.cn match DomainKeyword(google) using PROXY[trojan]
11:11:54.760   Debug: [PKG] 172.31.255.253:37608 --> r7---sn-2x3eln7r.xn--ngstr-lra8j.com:443 by 10212[com.android.vending]
11:11:55.398    Info: [TCP] 172.31.255.253:37608 --> r7---sn-2x3eln7r.xn--ngstr-lra8j.com match RuleSet(proxy) using PROXY[trojan]
11:12:00.117   Debug: [PKG] 172.31.255.253:38331 --> services.googleapis.cn:443 by -1[]
11:12:00.369   Debug: [PKG] 172.31.255.253:37614 --> r7---sn-2x3eln7r.xn--ngstr-lra8j.com:443 by 10212[com.android.vending]
11:12:00.678    Info: [UDP] 172.31.255.253:38331 --> services.googleapis.cn match DomainKeyword(google) using PROXY[trojan]
11:12:00.886    Info: [TCP] 172.31.255.253:37614 --> r7---sn-2x3eln7r.xn--ngstr-lra8j.com match RuleSet(proxy) using PROXY[trojan]

**Comment by Loyalsoldier** [comment]
应该是 `googleapis.cn` 这个域名的问题。

**Comment by lu989898** [comment]
googleapis.cn这个域名我单独加了一条规则，看日志应该也是走了代理的，可以请教下该如何解决么。

**Comment by Cielstar** [comment]
安卓怎么填规则啊，没找到填的地方·
