### ISSUE TITLE
请教作者 GEOIP,,DIRECT 规则是起什么作用？

### ISSUE THREAD

**Issue by jdjxk** [Loyalsoldier/clash-rules#50]
GEOIP,,DIRECT 中间留空会调用什么规则？

**Comment by Blink1024** [comment]
> 会匹配私有 IP 地址（局域网），但是目前版本的 Clash 不知道这条规则是否还能生效，没有验证。

请教一下,已经有`RULE-SET,lancidr,DIRECT`了,为什么还要`GEOIP,,DIRECT`这条呢,这两条不是等价的吗

**Comment by dyxushuai** [comment]
在 clash premium 里行为有问题，貌似匹配了所有地址

**Comment by dyxushuai** [comment]
[代码](https://github.com/Dreamacro/clash/blob/a20b9a3960/rule/geoip.go#L26-L28)
需要写成：GEOIP,LAN, DIRECT 才可以匹配局域网
