### ISSUE TITLE
白名单模式下如何屏蔽BT下载流量呢？

### ISSUE THREAD

**Issue by yusiwen** [Loyalsoldier/clash-rules#55]
如题，谢谢各位大佬

**Comment by Loyalsoldier** [comment]
新增规则 `PROCESS-NAME,软件进程名称,REJECT`

**Comment by yusiwen** [comment]
@Loyalsoldier 谢谢！我回去试试看，还有个疑问：我的BT下载部署在NAS上的，这个可以用PROCESS-NAME来过滤么？

**Comment by Loyalsoldier** [comment]
Premium 版本的 Clash 支持使用 PROCESS-NAME 规则

**Comment by yusiwen** [comment]
@Loyalsoldier 我的BT下载是那另一台机器上，OpenClash部署在路由器上，不在一起，这样也能用PROCESS-NAME来过滤么？

**Comment by Loyalsoldier** [comment]
不同机器当然不能用 PROCESS-NAME 规则。用来源 IP + 端口

**Comment by yusiwen** [comment]
好的，谢谢。我回去试试看
