### ISSUE TITLE
cdn.jsdelivr.net不應該走代理吧？

### ISSUE THREAD

**Issue by sammimk830** [Loyalsoldier/clash-rules#59]
https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
在这能發現jsdelivr.net的，但是cdn.jsdelivr.net是直接大陸IP的，是有什麼原因的嗎？

**Comment by Loyalsoldier** [comment]
没什么原因。请自己添加到直连规则。
