### ISSUE TITLE
direct清单里面有很多google域名

### ISSUE THREAD

**Issue by zdfdreamfactory** [Loyalsoldier/clash-rules#61]
例如googleapis.com是无法访问的

用这个规则，最新版的clash for android，可以访问play商店，但是下载应用一直不成功，没有进度条（或者说进度条一直为0），换用其他的软件正常（比如shadowsocks android)，感觉应该是规则的原因

**Comment by Loyalsoldier** [comment]
建议把 Google 相关域名加入到代理规则。

**Comment by DeruiDENG** [comment]
遇到同样的问题，为什么Google域名被放在direct清单呢？

**Comment by Loyalsoldier** [comment]
> 遇到同样的问题，为什么Google域名被放在direct清单呢？

把 `- RULE-SET,google,DIRECT` 改为 `- RULE-SET,google,PROXY` 即可。

**Comment by WoadZS** [comment]
规则前面放 ` - DOMAIN-KEYWORD,google,PROXY` 就可以
