### ISSUE TITLE
[feature request] 新增国区游戏的 rule-provider

### ISSUE THREAD

**Issue by ZeppLu** [Loyalsoldier/clash-rules#65]
如题，希望可以在 GitHub Actions 中顺便再将 https://github.com/v2fly/domain-list-community/blob/master/data/category-games 里带有 `@cn` 属性的网址生成到一个新的列表里面，方便大家使用。

**Comment by Loyalsoldier** [comment]
目前不打算一个个列表新增。期待未来项目重构吧。
