### ISSUE TITLE
mail-ads.google.com可能会导致gmail无法正常访问

### ISSUE THREAD

**Issue by tony1016** [Loyalsoldier/clash-rules#78]
reject中的mail-ads.google.com，其解析地址和mail.bankcomm.com是一致的，似乎会导致redir时，该IP的访问被标记成了mail-ads.google.com而被拒绝。请删除它。
```
dig mail.google.com +short
googlemail.l.google.com.
216.58.195.69

dig mail-ads.google.com +short
googlemail.l.google.com.
216.58.195.69
```

最终导致clash判断问题：
```
[TCP] 192.168.31.7:52365 --> mail-ads.google.com:443 match RuleSet(reject) using REJECT
```

**Comment by tony1016** [comment]
似乎把proxy调在前面就好了

**Comment by tony1016** [comment]
我以为我把proxy放在前面，就可以解决，但是依然匹配到reject，这是为什么呢？？

**Comment by Loyalsoldier** [comment]
应该是 Clash 的规则匹配问题，到 Clash 提 issue。

**Comment by tony1016** [comment]
很可能是openclash这个分支的问题

Loyalsoldier ***@***.***> 于2022年4月4日周一 14:26写道：
