### ISSUE TITLE
why clash dashboard  http://yacd.haishan.me/ math proxy rule?

### ISSUE THREAD

**Issue by Ehco1996** [Loyalsoldier/clash-rules#8]
<img width="1080" alt="截屏2020-11-04 上午7 33 57" src="https://user-images.githubusercontent.com/24697284/98052097-4358de00-1e70-11eb-8218-abc0bb544d2b.png">

为啥yacd没写在规则里呀

用的是：白名单模式 Rules 配置方式（推荐） + Rule Providers 

如果是漏了希望能修一下规则

**Comment by Loyalsoldier** [comment]
Done in https://github.com/Loyalsoldier/clash-rules/commit/594f81515ed69f4121c819573f2ecc5ecef7b5fa

**Comment by Loyalsoldier** [comment]
Please add that two rules into your configuration.

**Comment by Ehco1996** [comment]
thanks ~
