### ISSUE TITLE
mihoyo.com应该从proxy中移除吧？

### ISSUE THREAD

**Issue by teraStars** [Loyalsoldier/clash-rules#80]
就是原神的出品公司啊，国内的啊。

**Comment by Loyalsoldier** [comment]
mihoyo.com 在 direct 和 proxy 里都存在，将 direct 规则放在 proxy 规则前面/上面即可。

**Comment by teraStars** [comment]
> mihoyo.com 在 direct 和 proxy 里都存在，将 direct 规则放在 proxy 规则前面/上面即可。

问题米哈游为什么要放在proxy中呢？它就是上海的公司啊，ip属于上海阿里云。

**Comment by Loyalsoldier** [comment]
上游有变化。等待本项目重构吧。
