### ISSUE TITLE
写了两个订阅转换的规则，直接适配rule-set的白名单模式

### ISSUE THREAD

**Issue by wyk19** [Loyalsoldier/clash-rules#86]
https://raw.githubusercontent.com/wyk19/subconverter-web/master/rules/base.yml
https://raw.githubusercontent.com/wyk19/subconverter-web/master/rules/rule-set.ini

**Comment by wyk19** [comment]
并且自己搭了一个subconverter，想测试我发的规则的可以试试：
https://subconverter-k2rb.onrender.com/

**Comment by pheotry** [comment]
好用
