### ISSUE TITLE
cdn域名无法下载规则集

### ISSUE THREAD

**Issue by HammerShaw** [Loyalsoldier/clash-rules#87]
cdn 的域名是挂了吗，昨天开始一直不行
![Uploading 微信截图_20220517084410.png…]()

**Comment by TigerBeanst** [comment]
`cdn.jsdelivr.net` 从昨天下午开始又被污染了

**Comment by Loyalsoldier** [comment]
感谢提醒，已去除 cdn.jsdelivr.net 链接。
