### ISSUE TITLE
cdn.jsdelivr.net已被墙

### ISSUE THREAD

**Issue by Qvisl9** [Loyalsoldier/clash-rules#90]
cdn.jsdelivr.net已被墙，换成github订阅源，显示The requsted name is valid,but no data of the requested type was found。没有找到数据，该如何解决？

**Comment by Loyalsoldier** [comment]
感谢提醒，已去除 cdn.jsdelivr.net 链接。URL 不完全一样，不能只更换域名。

**Comment by Qvisl9** [comment]
麻烦指导下，我重新导入github的订阅源，还是出现这个问题。

Loyalsoldier ***@***.***> 于2022年5月21日周六 10:29写道：

**Comment by Qvisl9** [comment]
url我也是导入你github给出的，似乎还是不行，不知道是哪里出了问题。

Loyalsoldier ***@***.***> 于2022年5月21日周六 10:29写道：

**Comment by Loyalsoldier** [comment]
搜了一下，应该是你本地 DNS 污染，换个公共 DNS

**Comment by Qvisl9** [comment]
能具体说下吗，这方便我并不是很懂，有什么好的推荐公共dns，又该如何添加到cfw，如果你有空，能否抽空指导下？

Loyalsoldier ***@***.***> 于2022年5月21日周六 12:54写道：

**Comment by Loyalsoldier** [comment]
https://zhuanlan.zhihu.com/p/265364903

**Comment by Qvisl9** [comment]
我按照你的方法，换了dns服务器，但也只能部分更新成功，去网上搜了dns服务器地址，大多测试了下，都无法全部更新成功。

Loyalsoldier ***@***.***> 于2022年5月21日周六 13:10写道：
