### ISSUE TITLE
在线更新的配置的文件如何保留其规则？

### ISSUE THREAD

**Issue by netsonicyxf** [Loyalsoldier/clash-rules#91]
Clash 配置文件是在线更新的，按照改规则使用说明

> 要想使用本项目的规则集，只需要在 Clash 配置文件中添加如下 rule-providers 和 rules。

添加的规则会不会在更新配置文件后丢失？如果会的话，如何在不用手动黏贴的前提下保留规则？

**Comment by KodachiGitHub** [comment]
使用配置文件预处理功能 
https://docs.cfw.lbyczf.com/contents/parser.html

**Comment by Loyalsoldier** [comment]
使用 proxy-provider 即可：https://lancellc.gitbook.io/clash/clash-config-file/proxy-provider

**Comment by ThoundsN** [comment]
> 使用 proxy-provider 即可：https://lancellc.gitbook.io/clash/clash-config-file/proxy-provider

这个链接失效了

**Comment by Loyalsoldier** [comment]
@ThoundsN 

参考这个配置文件：https://github.com/Loyalsoldier/clash-rules/blob/hidden/config.yaml
