### ISSUE TITLE
initial rule provider reject error:context deadline exceeded

### ISSUE THREAD

**Issue by solologo** [Loyalsoldier/clash-rules#92]
error reported

**Comment by Loyalsoldier** [comment]
网络问题。看看所在地区是否 DNS 污染了域名 `raw.githubusercontent.com` ；换一个公共 DNS

**Comment by yuyang0** [comment]
这个问题看起来是clash的超时时间太短，只有5s，更新provider似乎没有走代理，直连下载那些大文件动不动几十秒，所以基本不会成功，这不是dns的问题，换dns解决不了

**Comment by solologo** [comment]
> raw.githubusercontent.com

使用的是114.114.114.114DNS，更新pprovider是使用的全局代理，依旧没有成功

**Comment by solologo** [comment]
> 这个问题看起来是clash的超时时间太短，只有5s，更新provider似乎没有走代理，直连下载那些大文件动不动几十秒，所以基本不会成功，这不是dns的问题，换dns解决不了

全局代理的

**Comment by yuyang0** [comment]
更新不了，这个项目的用处也就大打折扣了

**Comment by kayanouriko** [comment]
我改 DNS 也不管用, 但是通过下面方法可以下载到文件.

> 通过 https://www.ipaddress.com/ 查询 raw.githubusercontent.com 的 ip, 将他们全部加入 host 就可以了.

会看到 clash 文件夹下面会生成 ruleset 文件夹会有文件下载成功.
中途我这边还是有报错, 多点几次配置文件让他继续下载直到下载完成.

照该项目的更新间隔来看, 没了 jsDelivr  每次这样更新挺折磨的.
翻了一下网上讨论这问题的就没几个地方, 没翻到没啥好的解决方案.

好在 proxy-provider 也支持本地文件读取.
最后我还是推荐自行下载 txt 文件, 采用本地文件读取的配置方案吧.
反正规则通常也不太需要保持更新, 想起来再更新一下也没啥大问题.

**Comment by solologo** [comment]
> 我改 DNS 也不管用, 但是通过下面方法可以下载到文件.
> 
> > 通过 https://www.ipaddress.com/ 查询 raw.githubusercontent.com 的 ip, 将他们全部加入 host 就可以了.
> 
> 会看到 clash 文件夹下面会生成 ruleset 文件夹会有文件下载成功. 中途我这边还是有报错, 多点几次配置文件让他继续下载直到下载完成.
> 
> 照该项目的更新间隔来看, 没了 jsDelivr 每次这样更新挺折磨的. 翻了一下网上讨论这问题的就没几个地方, 没翻到没啥好的解决方案.
> 
> 好在 rule-providers 和 proxy-provider 一样也支持本地文件读取. 最后我还是推荐自行下载 txt 文件, 采用本地文件读取的配置方案吧. 反正规则通常也不太需要保持更新, 想起来再更新一下也没啥大问题.

比较神奇的是，浏览器打开txt的url毫无障碍，应该不是host解析问题。
早知道可以本地就不这么麻烦了。缺失多点击几十次就可以下载了。。。。
感谢。

**Comment by ms2008** [comment]
可以替换成加速地址，e.g. `https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt`

**Comment by WillingAC** [comment]
> 好在 rule-providers 和 proxy-provider 一样也支持本地文件读取.
> 最后我还是推荐自行下载 txt 文件, 采用本地文件读取的配置方案吧.
> 反正规则通常也不太需要保持更新, 想起来再更新一下也没啥大问题.

自行下载原文件放到本地读取可以成功切换Profile；


> 可以替换成加速地址，e.g. `https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt`

感谢！用加速地址第一次更新提示DNS解析错误（Profile中用了默认配置中的DNS参数，不知道更新Provider是否用Profile指定的DNS）。第二次开始，几秒～十多秒可成功更新。

**Comment by Loyalsoldier** [comment]
`cdn.jsdelivr.net` 又可以重新访问了，类似这样：https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt

**Comment by ys3322** [comment]
我换成手机热点网络，就可以解决这个下载规则报错的问题了。感觉可能是dns或者公司网络被污染了。

**Comment by dawnflyc** [comment]
在界面配置的后面可以打开代码，翻到对应代码处，如果你已经下载好的，会显示“显示实际文件”，如果出错了，则会显示“复制MD5”类似的（因为我弄好了才来的）。你复制了这个MD5后，在C:\Users\<你的用户>\.config\clash\providers\rule创建一个文本，然后将名字改为复制的MD5（复制自带扩展名），然后手动访问，然后将内容复制到刚才建的文本里面，就可以了。

**Comment by DonaldTrump-coder** [comment]
> 在界面配置的后面可以打开代码，翻到对应代码处，如果你已经下载好的，会显示“显示实际文件”，如果出错了，则会显示“复制MD5”类似的（因为我弄好了才来的）。你复制了这个MD5后，在C:\Users<你的用户>.config\clash\providers\rule创建一个文本，然后将名字改为复制的MD5（复制自带扩展名），然后手动访问，然后将内容复制到刚才建的文本里面，就可以了。
你在说什么？
