### ISSUE TITLE
google 规则集加入 play 商店 下载相关域名

### ISSUE THREAD

**Issue by eastarpen** [Loyalsoldier/clash-rules#95]
`rules` 复制本项目 `README` 白名单模式,  MIUI12 playe 商店无法下载

添加两个域名后正常

```
  - DOMAIN-SUFFIX,xn--ngstr-lra8j.com,PROXY
  - DOMAIN-SUFFIX,googleapis.cn,PROXY
 ```

希望能直接添加到规则集中

rules 配置如下

```
rules:
  - DOMAIN-SUFFIX,xn--ngstr-lra8j.com,PROXY
  - DOMAIN-SUFFIX,googleapis.cn,PROXY

  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,PROXY
  - RULE-SET,apple,PROXY
  - RULE-SET,google,PROXY
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
 ```

> Q: 为什么我的 Google Play Services 无法连接 / 为什么我的 Google Play 无法登录，提示错误 DF-DFERH-01 / 我的日志里面 googleapis.cn 走的是直连 DIRECT。
> 
> A: 部分国产 ROM 连接 Google Play Services 使用的是 googleapis.cn ，而不是 googleapis.com 。无法连接的一个可能的原因是 googleapis.cn 的规则匹配问题，它优先匹配了CN字段，导致走的直连。解决方法是修改配置文件，在规则内最前方（ Rule: 换行后第一条） 添加下面一条规则: 
> 
> ` - DOMAIN-SUFFIX, googleapis.cn, Proxy`

**Comment by Loyalsoldier** [comment]
感谢提醒，等上游项目处理。

**Comment by DustinWin** [comment]
我就遇到了这个问题，Google Play Store 无法下载更新应用，感谢答疑。

**Comment by bash99** [comment]
googleapis.cn 这个域名在gfw列表中，为何不在proxy列表中？
我是加了一行 
```
  - RULE-SET,gfw,PROXY
```
解决

**Comment by DustinWin** [comment]
> googleapis.cn 这个域名在gfw列表中，为何不在proxy列表中？ 我是加了一行
> 
> ```
>   - RULE-SET,gfw,PROXY
> ```
> 
> 解决

我发现 googleapis.cn 也在 direct （直连域名列表）列表中，单独将 direct 列表设置为 proxy 也可以解决，很显然只适合临时解决。或者按楼主所说方法也可。
